/**
 * Utilities for dynamically managing and injecting incident context into
 * AI Agent prompts when on incident pages (/incidents/:id, /incidents-simple/:id)
 * and when assigning tasks to AI agents.
 */

export interface IncidentPromptObservable {
  type?: string;
  value?: string;
  archived?: boolean;
}

export interface IncidentPromptTask {
  id?: string;
  title?: string;
  status?: string;
  category?: string;
  description?: string;
}

export interface ActiveIncidentPromptContext {
  id?: string;
  title?: string;
  severity?: string;
  status?: string;
  description?: string;
  observables?: IncidentPromptObservable[];
  tasks?: IncidentPromptTask[];
  rawOCSF?: Record<string, any>;
}

// Global window / globalThis key for cross-component access
const GLOBAL_INCIDENT_KEY = '__shuffleActiveIncidentContext';

const getGlobalScope = (): any => {
  if (typeof globalThis !== 'undefined') return globalThis;
  if (typeof window !== 'undefined') return window;
  if (typeof global !== 'undefined') return global;
  return null;
};

/**
 * Registers the active incident context globally.
 */
export const setActiveIncidentPromptContext = (info: ActiveIncidentPromptContext | null) => {
  const scope = getGlobalScope();
  if (!scope) return;
  if (info) {
    scope[GLOBAL_INCIDENT_KEY] = { ...info };
  } else {
    delete scope[GLOBAL_INCIDENT_KEY];
  }
};

/**
 * Retrieves the currently active incident context.
 */
export const getActiveIncidentPromptContext = (): ActiveIncidentPromptContext | null => {
  const scope = getGlobalScope();
  if (!scope) return null;
  const info = scope[GLOBAL_INCIDENT_KEY];
  if (info && typeof info === 'object') {
    return info as ActiveIncidentPromptContext;
  }
  return null;
};

/**
 * Clears the active incident context.
 */
export const clearActiveIncidentPromptContext = () => {
  setActiveIncidentPromptContext(null);
};

export const INCIDENT_PROMPT_DELIMITER_START = '=== INCIDENT CONTEXT ===';
export const INCIDENT_PROMPT_DELIMITER_END = '=== END INCIDENT CONTEXT ===';

/**
 * Format raw observable type into a human-readable security identifier.
 */
export const formatObservableType = (type?: string): string => {
  if (!type) return 'Indicator';
  const clean = type.toLowerCase().trim();
  switch (clean) {
    case 'ip':
    case 'ipv4':
    case 'ip_address':
      return 'IPv4';
    case 'ipv6':
      return 'IPv6';
    case 'hash':
    case 'sha256':
    case 'file_hash':
      return 'SHA256';
    case 'md5':
      return 'MD5';
    case 'sha1':
      return 'SHA1';
    case 'hostname':
    case 'host':
    case 'endpoint':
      return 'Hostname';
    case 'domain':
      return 'Domain';
    case 'url':
      return 'URL';
    case 'user':
    case 'username':
    case 'account':
      return 'User';
    case 'email':
      return 'Email';
    case 'process':
    case 'process_name':
      return 'Process';
    case 'file':
    case 'filename':
      return 'File';
    default:
      return type.charAt(0).toUpperCase() + type.slice(1);
  }
};

/**
 * Checks whether a prompt already contains injected incident context.
 */
export const isIncidentInjectedPrompt = (prompt?: string | null): boolean => {
  if (!prompt || typeof prompt !== 'string') return false;
  return (
    prompt.includes(INCIDENT_PROMPT_DELIMITER_START) ||
    prompt.includes('OPERATIONAL DIRECTIVES:') ||
    prompt.includes('INCIDENT OBSERVABLES / IOCs:')
  );
};

/**
 * Checks if a prompt was generated by the legacy bare auto-assign format
 * which lacked observables and caused agents to call get_incident.
 */
export const isLegacyTaskPrompt = (prompt?: string | null): boolean => {
  if (!prompt || typeof prompt !== 'string') return false;
  const trimmed = prompt.trim();
  return (
    trimmed.startsWith('Please automatically handle and resolve the following task for incident') &&
    !isIncidentInjectedPrompt(trimmed)
  );
};

/**
 * Builds an optimized, context-rich prompt for an incident task.
 * Directly provides task details, incident summary, all observables/IOCs,
 * playbook status, and explicit directives preventing redundant get_incident calls.
 */
export const buildTaskAiPrompt = (
  task: {
    id?: string;
    title?: string;
    description?: string;
    category?: string;
  },
  context?: ActiveIncidentPromptContext | null,
  options?: { reRun?: boolean }
): string => {
  const taskTitle = task.title?.trim() || 'Untitled task';
  const taskCategory = task.category?.trim();
  const taskDesc = task.description?.trim();

  const ctx = context || getActiveIncidentPromptContext() || {};
  const incidentRef = ctx.id ? `#${ctx.id}` : '';
  const incidentTitle = ctx.title?.trim() || 'Incident';
  const severity = ctx.severity || 'Medium';
  const status = ctx.status || 'In Progress';
  const description = ctx.description?.trim() || 'No description provided.';

  // Build formatted, deduplicated observables list
  const seenObservables = new Set<string>();
  const formattedObservables: string[] = [];

  if (Array.isArray(ctx.observables)) {
    for (const obs of ctx.observables) {
      if (!obs || obs.archived || !obs.value?.trim()) continue;
      const val = obs.value.trim();
      const typeLabel = formatObservableType(obs.type);
      const key = `${typeLabel.toLowerCase()}:${val.toLowerCase()}`;
      if (seenObservables.has(key)) continue;
      seenObservables.add(key);
      formattedObservables.push(`- ${typeLabel}: ${val}`);
    }
  }

  const observablesBlock =
    formattedObservables.length > 0
      ? formattedObservables.slice(0, 50).join('\n') +
        (formattedObservables.length > 50
          ? `\n- (... and ${formattedObservables.length - 50} more observables)`
          : '')
      : '- None recorded yet';

  // Build sibling playbook tasks
  const playbookTasks = Array.isArray(ctx.tasks) ? ctx.tasks : [];
  const taskLines: string[] = [];

  for (const t of playbookTasks) {
    if (!t || !t.title?.trim()) continue;
    const isCurrent = task.id && String(t.id).trim() === String(task.id).trim();
    const tStatus = (t.status || '').toLowerCase();
    const statusMark =
      tStatus === 'completed' || tStatus === 'done'
        ? '[Done]'
        : tStatus === 'in_progress' || tStatus === 'executing'
        ? '[In Progress]'
        : '[Pending]';
    const cat = t.category ? ` (${t.category})` : '';
    const currentMarker = isCurrent ? ' <- CURRENT ASSIGNED TASK' : '';
    taskLines.push(`- ${statusMark} ${t.title.trim()}${cat}${currentMarker}`);
  }

  const tasksBlock = taskLines.length > 0 ? taskLines.join('\n') : '- None listed';

  const categoryLine = taskCategory ? `Phase: ${taskCategory}\n` : '';
  const detailsLine = taskDesc ? `Task Details:\n${taskDesc}\n` : '';

  return `Please handle and resolve the following task for incident ${incidentRef} ("${incidentTitle}"):

TASK TO EXECUTE:
- Task: ${taskTitle}
${categoryLine}${detailsLine}
${INCIDENT_PROMPT_DELIMITER_START}
INCIDENT OVERVIEW:
- Incident ID: ${ctx.id || 'N/A'}
- Title: ${incidentTitle}
- Severity: ${severity} | Status: ${status}
- Summary: ${description}

INCIDENT OBSERVABLES / IOCs:
${observablesBlock}

PLAYBOOK TASKS:
${tasksBlock}
${INCIDENT_PROMPT_DELIMITER_END}

OPERATIONAL DIRECTIVES:
1. All relevant incident details, observables, and context have been provided directly above.
2. DO NOT call "get_incident" or attempt to fetch this incident from Shuffle_Incidents.
3. Directly analyze the provided observables and execute the required investigation, containment, or remediation actions for this task: "${taskTitle}".
4. Clearly report your findings, actions taken, and recommended next steps.`;
};

/**
 * Extracts a concise display prompt (e.g. "Task: <title>") from an incident-injected
 * prompt so headers, drawer titles, and rerun inputs remain compact and readable.
 */
export const extractCleanIncidentPrompt = (prompt?: string | null): string => {
  if (!prompt || typeof prompt !== 'string') return '';
  const trimmed = prompt.trim();

  // 1. Task prompts: extract "- Task: <title>"
  const taskMatch = trimmed.match(/TASK TO EXECUTE:\s*\n\s*-\s*Task:\s*([^\n]+)/i);
  if (taskMatch && taskMatch[1]?.trim()) {
    return `Task: ${taskMatch[1].trim()}`;
  }

  // 2. Fallback for legacy task prompts: "Task: <title>"
  const legacyMatch = trimmed.match(/\n\s*Task:\s*([^\n]+)/i);
  if (legacyMatch && legacyMatch[1]?.trim()) {
    return `Task: ${legacyMatch[1].trim()}`;
  }

  // 3. User ad-hoc question: extract the text before delimiter or after
  if (trimmed.includes(INCIDENT_PROMPT_DELIMITER_START)) {
    const before = trimmed.split(INCIDENT_PROMPT_DELIMITER_START)[0]?.trim();
    if (before) return before;
  }

  return trimmed;
};

/**
 * Composes user input with incident context if on an incident page and not already injected.
 */
export const composeIncidentPromptInput = (
  rawInput: string,
  context?: ActiveIncidentPromptContext | null
): string => {
  if (!rawInput || typeof rawInput !== 'string') return '';
  const trimmed = rawInput.trim();
  if (isIncidentInjectedPrompt(trimmed)) {
    return trimmed;
  }

  const ctx = context || getActiveIncidentPromptContext();
  if (!ctx || !ctx.id) {
    return trimmed;
  }

  const incidentRef = ctx.id ? `#${ctx.id}` : '';
  const incidentTitle = ctx.title?.trim() || 'Incident';
  const severity = ctx.severity || 'Medium';
  const status = ctx.status || 'In Progress';
  const description = ctx.description?.trim() || 'No description provided.';

  // Format observables
  const seenObservables = new Set<string>();
  const formattedObservables: string[] = [];

  if (Array.isArray(ctx.observables)) {
    for (const obs of ctx.observables) {
      if (!obs || obs.archived || !obs.value?.trim()) continue;
      const val = obs.value.trim();
      const typeLabel = formatObservableType(obs.type);
      const key = `${typeLabel.toLowerCase()}:${val.toLowerCase()}`;
      if (seenObservables.has(key)) continue;
      seenObservables.add(key);
      formattedObservables.push(`- ${typeLabel}: ${val}`);
    }
  }

  const observablesBlock =
    formattedObservables.length > 0
      ? formattedObservables.slice(0, 50).join('\n')
      : '- None recorded yet';

  return `${trimmed}

${INCIDENT_PROMPT_DELIMITER_START}
INCIDENT CONTEXT:
- Incident: ${incidentRef} ("${incidentTitle}")
- Severity: ${severity} | Status: ${status}
- Summary: ${description}

INCIDENT OBSERVABLES / IOCs:
${observablesBlock}
${INCIDENT_PROMPT_DELIMITER_END}

DIRECTIVES:
- Relevant incident details and observables are provided above. Do not call "get_incident" unless raw external logs are required.`;
};
