/**
 * OnCallScheduleManager — shared on-call schedule UI used by:
 *   • /users  (Tenant Admin → User Management tab)
 *   • /onboarding  (Automate step → "Assign & Escalate" expandable card)
 *
 * Single source of truth for the per-user availability windows, escalation
 * tiers, import dialog, and weekly timeline — backed by the
 * `assignment_schedules` config datastore item. Both surfaces always render
 * the identical experience and stay in sync as the config changes.
 *
 * Pulled out of UsersPage.tsx so the onboarding step does not have to
 * re-implement (and inevitably drift from) the same UI.
 */

import { Plus as AddIcon, Pencil as EditIcon, Trash2 as DeleteIcon, ChevronDown as ExpandMoreIcon, Clock as ScheduleIcon, Upload as UploadIcon, CalendarDays as CalendarIcon, Clock as AccessTimeIcon, User as PersonIcon } from 'lucide-react';
import { useState, useEffect, useCallback, useMemo } from 'react';
import {
  Box,
  Typography,
  Paper,
  Chip,
  Avatar,
  CircularProgress,
  Alert,
  IconButton,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Stack,
  Collapse,
  LinearProgress,
  Switch,
  FormControlLabel,
} from '@mui/material';
import { motion } from 'framer-motion';
import { toast } from '@/lib/toast';
import AgentIcon from '@/Shuffle-Core/components/AgentIcon';
import { setDatastoreItem, getDatastoreItem, DATASTORE_CATEGORIES } from '@/Shuffle-Core/datastore';
import { WeeklyScheduleTimeline, AI_AGENT_SCHEDULE } from '@/components/users/WeeklyScheduleTimeline';
import { ScheduleImportDialog } from '@/components/users/ScheduleImportDialog';
import { AddUserDialog } from '@/components/users/AddUserDialog';
import { UserRoleSelect } from '@/components/users/UserRoleSelect';

// ── Types ────────────────────────────────────────────────────────────────────
export type EscalationLevel = 'tier1' | 'tier2' | 'tier3' | 'manager';

export const ESCALATION_LABELS: Record<EscalationLevel, string> = {
  tier1: 'Tier 1',
  tier2: 'Tier 2',
  tier3: 'Tier 3',
  manager: 'Manager',
};

export const ESCALATION_DESCRIPTIONS: Record<EscalationLevel, string> = {
  tier1: 'First Response',
  tier2: 'Specialist',
  tier3: 'Expert',
  manager: 'Escalation',
};

export const ESCALATION_COLORS: Record<EscalationLevel, string> = {
  tier1: '#22c55e',
  tier2: '#3b82f6',
  tier3: '#f59e0b',
  manager: '#ef4444',
};

export interface ScheduleEntry {
  id: string;
  startDate: string;
  endDate: string;
  startTime: string;
  endTime: string;
  timezone: string;
  daysOfWeek: number[];
}

export interface UserSchedule {
  userId: string;
  userName: string;
  userEmail: string;
  escalationLevel: EscalationLevel;
  schedules: ScheduleEntry[];
  enabled: boolean;
}

/**
 * Default Assign & Escalate policy.
 *
 * Used as the routing fallback whenever no human is actively on-call for a
 * given tier. The baseline rule is: AI Agent always backs Tier 1, and any
 * uncovered tier escalates upward.
 *
 * The policy is recomputed and persisted alongside `userSchedules` on every
 * save, so the cached config always exposes a usable routing table.
 */
export interface DefaultAssignmentPolicy {
  /** Tier → routing entry. `primary` is the preferred assignee when the tier
   *  is configured; `fallback` kicks in when no human is on-call right now.
   *  Tier 1's fallback is always the AI Agent. */
  tiers: Record<EscalationLevel, {
    primary: 'ai_agent' | 'human' | 'none';
    fallback: 'ai_agent' | 'none';
    /** Tier to escalate to if unacknowledged. `null` = top of chain. */
    escalateTo: EscalationLevel | null;
  }>;
  /** When true, this policy was generated by the system rather than the user. */
  generated: boolean;
}

export interface AssignmentConfig {
  userSchedules: UserSchedule[];
  updatedAt: string;
  autoInitialized?: boolean;
  defaultPolicy?: DefaultAssignmentPolicy;
}

/**
 * Build the default Assign & Escalate policy from the current schedules.
 *
 * - Tier 1 always has the AI Agent as `fallback`. If no human covers Tier 1,
 *   the AI Agent is also the `primary`.
 * - Higher tiers fall back to escalation (no AI Agent) so high-stakes
 *   incidents always reach a real responder.
 */
export const computeDefaultPolicy = (schedules: UserSchedule[]): DefaultAssignmentPolicy => {
  const hasHumanCoverage = (level: EscalationLevel) =>
    schedules.some(s => s.enabled && s.escalationLevel === level && s.schedules.length > 0);

  const order: EscalationLevel[] = ['tier1', 'tier2', 'tier3', 'manager'];

  const tiers = order.reduce((acc, level, idx) => {
    const next = order[idx + 1] ?? null;
    const humanCovers = hasHumanCoverage(level);

    if (level === 'tier1') {
      // AI Agent is always the safety net for Tier 1, and becomes the primary
      // assignee outright when no human is configured to cover it.
      acc[level] = {
        primary: humanCovers ? 'human' : 'ai_agent',
        fallback: 'ai_agent',
        escalateTo: next,
      };
    } else {
      acc[level] = {
        primary: humanCovers ? 'human' : 'none',
        fallback: 'none',
        escalateTo: next,
      };
    }
    return acc;
  }, {} as DefaultAssignmentPolicy['tiers']);

  return { tiers, generated: true };
};

export interface OnCallUser {
  id: string;
  username: string;
  role?: string;
  active?: boolean;
}

interface OnCallScheduleManagerProps {
  users: OnCallUser[];
  loading?: boolean;
  /** When true, hides the Team Members header + stats so the component slots
   *  cleanly into a parent that already provides its own framing (e.g. the
   *  onboarding "Assign & Escalate" expanded card). */
  compact?: boolean;
  onRefreshUsers?: () => void | Promise<void>;
}

// ── Constants & helpers ──────────────────────────────────────────────────────
const DAYS_OF_WEEK = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const generateId = () => Math.random().toString(36).substring(2, 12);

const createDefaultSchedule = (): ScheduleEntry => ({
  id: generateId(),
  startDate: new Date().toISOString().split('T')[0],
  endDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  startTime: '09:00',
  endTime: '17:00',
  timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
  daysOfWeek: [1, 2, 3, 4, 5],
});

const containerVariants = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.05 } },
};

const cardVariants = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0 },
};

// ── Component ────────────────────────────────────────────────────────────────
export const OnCallScheduleManager = ({
  users,
  loading = false,
  compact = false,
  onRefreshUsers,
}: OnCallScheduleManagerProps) => {
  const [localUsers, setLocalUsers] = useState<OnCallUser[]>(users);
  const [addUserOpen, setAddUserOpen] = useState(false);

  useEffect(() => {
    setLocalUsers(users);
  }, [users]);

  const handleRoleChanged = useCallback((userId: string, newRole: string) => {
    setLocalUsers((prev) =>
      prev.map((u) => (u.id === userId ? { ...u, role: newRole } : u))
    );
    if (onRefreshUsers) {
      onRefreshUsers();
    }
  }, [onRefreshUsers]);

  const [config, setConfig] = useState<AssignmentConfig>({ userSchedules: [], updatedAt: '' });
  const [configLoading, setConfigLoading] = useState(true);
  const [configError, setConfigError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);

  const [expandedRows, setExpandedRows] = useState<Set<string>>(new Set());

  const [scheduleDialogOpen, setScheduleDialogOpen] = useState(false);
  const [editingUserId, setEditingUserId] = useState<string | null>(null);
  const [editingEntry, setEditingEntry] = useState<ScheduleEntry | null>(null);

  const [escalationDialogOpen, setEscalationDialogOpen] = useState(false);
  const [escalationUserId, setEscalationUserId] = useState<string | null>(null);
  const [selectedLevel, setSelectedLevel] = useState<EscalationLevel>('tier1');

  const [importDialogOpen, setImportDialogOpen] = useState(false);
  const [timelineDialogOpen, setTimelineDialogOpen] = useState(false);

  const [entryStartDate, setEntryStartDate] = useState('');
  const [entryEndDate, setEntryEndDate] = useState('');
  const [entryStartTime, setEntryStartTime] = useState('09:00');
  const [entryEndTime, setEntryEndTime] = useState('17:00');
  const [entryDays, setEntryDays] = useState<number[]>([1, 2, 3, 4, 5]);

  // ── Persistence ────────────────────────────────────────────────────────────
  const loadConfig = useCallback(async () => {
    setConfigLoading(true);
    try {
      const response = await getDatastoreItem('assignment_schedules', DATASTORE_CATEGORIES.CONFIGURATION);
      if (response.success && response.item?.value) {
        const data: AssignmentConfig = typeof response.item.value === 'string'
          ? JSON.parse(response.item.value)
          : response.item.value;

        // Backfill the default policy on legacy configs that pre-date it so
        // the cached payload always exposes a usable Assign & Escalate plan.
        if (!data.defaultPolicy) {
          const backfilled: AssignmentConfig = {
            ...data,
            defaultPolicy: computeDefaultPolicy(data.userSchedules || []),
            updatedAt: new Date().toISOString(),
          };
          setConfig(backfilled);
          void setDatastoreItem('assignment_schedules', backfilled, DATASTORE_CATEGORIES.CONFIGURATION);
        } else {
          setConfig(data);
        }
      } else {
        // No saved config yet — seed the cache with the AI-Agent-handles-Tier-1
        // default so downstream consumers always have a routing plan to read.
        const seed: AssignmentConfig = {
          userSchedules: [],
          updatedAt: new Date().toISOString(),
          defaultPolicy: computeDefaultPolicy([]),
        };
        setConfig(seed);
        void setDatastoreItem('assignment_schedules', seed, DATASTORE_CATEGORIES.CONFIGURATION);
      }
    } catch (err) {
      setConfigError(err instanceof Error ? err.message : 'Failed to load configuration');
    } finally {
      setConfigLoading(false);
    }
  }, []);

  useEffect(() => { loadConfig(); }, [loadConfig]);

  const saveConfig = async (newConfig: AssignmentConfig, silent = false) => {
    setIsSaving(true);
    setConfigError(null);
    try {
      // Recompute the default policy on every save so the cache stays in sync
      // with the latest tier coverage (AI Agent fills any gaps at Tier 1).
      const configToSave: AssignmentConfig = {
        ...newConfig,
        updatedAt: new Date().toISOString(),
        defaultPolicy: computeDefaultPolicy(newConfig.userSchedules),
      };
      const response = await setDatastoreItem('assignment_schedules', configToSave, DATASTORE_CATEGORIES.CONFIGURATION);
      if (response.success) {
        setConfig(configToSave);
        if (!silent) toast.success('Schedule saved successfully');
      } else {
        throw new Error(response.error || 'Failed to save configuration');
      }
    } catch (err) {
      setConfigError(err instanceof Error ? err.message : 'Failed to save configuration');
    } finally {
      setIsSaving(false);
    }
  };

  // ── Auto-initialise rotation when no schedules exist yet ───────────────────
  // Default policy on first setup:
  //   • the current user is registered at every escalation level above Tier 1
  //     (Tier 2, Tier 3, Manager) so all escalations route to them by default;
  //   • other active users round-robin across Tier 1 / Tier 2 / Tier 3 to give
  //     a sensible starting rotation that the admin can refine.
  useEffect(() => {
    if (loading || configLoading || users.length === 0 || config.autoInitialized) return;
    if (config.userSchedules.length > 0) return;

    const activeUsers = users.filter(u => u.active !== false);
    if (activeUsers.length === 0) return;

    // Identify the current user from the cached getinfo payload so we can
    // wire them in as the catch-all escalation target.
    let currentUserId: string | null = null;
    try {
      const raw = localStorage.getItem('shuffle_user_info');
      if (raw) currentUserId = JSON.parse(raw)?.id || null;
    } catch { /* ignore */ }

    const currentUser = currentUserId
      ? activeUsers.find(u => u.id === currentUserId)
      : undefined;

    const newSchedules: UserSchedule[] = [];

    // Always-on schedule used for the catch-all escalation entries so the
    // current user is reachable 24/7 across every higher tier.
    const alwaysOnEntry = (): ScheduleEntry => ({
      id: generateId(),
      startDate: new Date().toISOString().split('T')[0],
      endDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      startTime: '00:00',
      endTime: '23:59',
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    });

    if (currentUser) {
      // Tier 1 stays a normal weekday window; Tier 2/3/Manager are 24/7
      // catch-alls so escalations always reach the current user.
      newSchedules.push({
        userId: currentUser.id,
        userName: currentUser.username,
        userEmail: currentUser.username,
        escalationLevel: 'tier1',
        schedules: [createDefaultSchedule()],
        enabled: true,
      });
      for (const level of ['tier2', 'tier3', 'manager'] as EscalationLevel[]) {
        newSchedules.push({
          userId: `${currentUser.id}::${level}`,
          userName: currentUser.username,
          userEmail: currentUser.username,
          escalationLevel: level,
          schedules: [alwaysOnEntry()],
          enabled: true,
        });
      }
    }

    // Round-robin remaining users across Tier 1 / 2 / 3 so the rotation
    // isn't a single-person setup.
    const others = activeUsers.filter(u => u.id !== currentUser?.id);
    others.forEach((user, index) => {
      let escalationLevel: EscalationLevel = 'tier1';
      if (index % 3 === 1) escalationLevel = 'tier2';
      else if (index % 3 === 2) escalationLevel = 'tier3';

      newSchedules.push({
        userId: user.id,
        userName: user.username,
        userEmail: user.username,
        escalationLevel,
        schedules: [createDefaultSchedule()],
        enabled: true,
      });
    });

    void saveConfig({
      userSchedules: newSchedules,
      updatedAt: new Date().toISOString(),
      autoInitialized: true,
    }, true);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, configLoading, users, config]);

  // ── Ensure the current user is always present in the rotation ──────────────
  // Even if the schedule was set up by someone else (auto-init already ran, or
  // another admin populated it), the currently signed-in user must appear at
  // Tier 1 plus the three escalation tiers so all escalations route back to
  // them by default. Missing entries are appended without touching anything
  // already configured.
  useEffect(() => {
    if (loading || configLoading || users.length === 0) return;

    let currentUserId: string | null = null;
    try {
      const raw = localStorage.getItem('shuffle_user_info');
      if (raw) currentUserId = JSON.parse(raw)?.id || null;
    } catch { /* ignore */ }
    if (!currentUserId) return;

    const currentUser = users.find(u => u.id === currentUserId);
    if (!currentUser) return;

    const alwaysOnEntry = (): ScheduleEntry => ({
      id: generateId(),
      startDate: new Date().toISOString().split('T')[0],
      endDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      startTime: '00:00',
      endTime: '23:59',
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    });

    const additions: UserSchedule[] = [];
    const requiredLevels: { level: EscalationLevel; userId: string; alwaysOn: boolean }[] = [
      { level: 'tier1',   userId: currentUser.id,                         alwaysOn: false },
      { level: 'tier2',   userId: `${currentUser.id}::tier2`,             alwaysOn: true  },
      { level: 'tier3',   userId: `${currentUser.id}::tier3`,             alwaysOn: true  },
      { level: 'manager', userId: `${currentUser.id}::manager`,           alwaysOn: true  },
    ];

    for (const req of requiredLevels) {
      // Already covered if any enabled entry exists for this user at this tier
      // (raw user id OR the namespaced escalation id).
      const covered = config.userSchedules.some(s =>
        s.enabled
        && s.escalationLevel === req.level
        && (s.userId === req.userId
            || s.userId === currentUser.id
            || s.userId.startsWith(`${currentUser.id}::`))
        && s.userName === currentUser.username
      );
      if (covered) continue;

      additions.push({
        userId: req.userId,
        userName: currentUser.username,
        userEmail: currentUser.username,
        escalationLevel: req.level,
        schedules: [req.alwaysOn ? alwaysOnEntry() : createDefaultSchedule()],
        enabled: true,
      });
    }

    if (additions.length === 0) return;

    void saveConfig({
      ...config,
      userSchedules: [...config.userSchedules, ...additions],
    }, true);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, configLoading, users, config]);

  // ── Helpers ────────────────────────────────────────────────────────────────
  const toggleRow = (userId: string) => {
    setExpandedRows(prev => {
      const next = new Set(prev);
      if (next.has(userId)) next.delete(userId); else next.add(userId);
      return next;
    });
  };

  const getUserSchedule = (userId: string): UserSchedule | undefined =>
    config.userSchedules.find(s => s.userId === userId);

  const handleToggleEnabled = (userId: string) => {
    const schedule = getUserSchedule(userId);
    if (schedule) {
      const newUserSchedules = config.userSchedules.map(s =>
        s.userId === userId ? { ...s, enabled: !s.enabled } : s
      );
      saveConfig({ ...config, userSchedules: newUserSchedules });
    } else {
      const user = users.find(u => u.id === userId);
      if (user) {
        const newSchedule: UserSchedule = {
          userId: user.id,
          userName: user.username,
          userEmail: user.username,
          escalationLevel: 'tier1',
          schedules: [createDefaultSchedule()],
          enabled: true,
        };
        saveConfig({ ...config, userSchedules: [...config.userSchedules, newSchedule] });
      }
    }
  };

  const handleEditEscalation = (userId: string) => {
    const schedule = getUserSchedule(userId);
    setEscalationUserId(userId);
    setSelectedLevel(schedule?.escalationLevel || 'tier1');
    setEscalationDialogOpen(true);
  };

  const handleSaveEscalation = () => {
    if (!escalationUserId) return;
    const schedule = getUserSchedule(escalationUserId);
    if (schedule) {
      const newUserSchedules = config.userSchedules.map(s =>
        s.userId === escalationUserId ? { ...s, escalationLevel: selectedLevel } : s
      );
      saveConfig({ ...config, userSchedules: newUserSchedules });
    } else {
      const user = users.find(u => u.id === escalationUserId);
      if (user) {
        const newSchedule: UserSchedule = {
          userId: user.id,
          userName: user.username,
          userEmail: user.username,
          escalationLevel: selectedLevel,
          schedules: [createDefaultSchedule()],
          enabled: true,
        };
        saveConfig({ ...config, userSchedules: [...config.userSchedules, newSchedule] });
      }
    }
    setEscalationDialogOpen(false);
  };

  const handleAddScheduleEntry = (userId: string) => {
    setEditingUserId(userId);
    setEditingEntry(null);
    setEntryStartDate(new Date().toISOString().split('T')[0]);
    setEntryEndDate(new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]);
    setEntryStartTime('09:00');
    setEntryEndTime('17:00');
    setEntryDays([1, 2, 3, 4, 5]);
    setScheduleDialogOpen(true);
  };

  const handleEditScheduleEntry = (userId: string, entry: ScheduleEntry) => {
    setEditingUserId(userId);
    setEditingEntry(entry);
    setEntryStartDate(entry.startDate);
    setEntryEndDate(entry.endDate);
    setEntryStartTime(entry.startTime);
    setEntryEndTime(entry.endTime);
    setEntryDays(entry.daysOfWeek);
    setScheduleDialogOpen(true);
  };

  const handleSaveScheduleEntry = () => {
    if (!editingUserId) return;
    const newEntry: ScheduleEntry = {
      id: editingEntry?.id || generateId(),
      startDate: entryStartDate,
      endDate: entryEndDate,
      startTime: entryStartTime,
      endTime: entryEndTime,
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      daysOfWeek: entryDays,
    };

    const schedule = getUserSchedule(editingUserId);
    if (schedule) {
      const newSchedules = editingEntry
        ? schedule.schedules.map(e => e.id === editingEntry.id ? newEntry : e)
        : [...schedule.schedules, newEntry];
      const newUserSchedules = config.userSchedules.map(s =>
        s.userId === editingUserId ? { ...s, schedules: newSchedules } : s
      );
      saveConfig({ ...config, userSchedules: newUserSchedules });
    } else {
      const user = users.find(u => u.id === editingUserId);
      if (user) {
        const newSchedule: UserSchedule = {
          userId: user.id,
          userName: user.username,
          userEmail: user.username,
          escalationLevel: 'tier1',
          schedules: [newEntry],
          enabled: true,
        };
        saveConfig({ ...config, userSchedules: [...config.userSchedules, newSchedule] });
      }
    }
    setScheduleDialogOpen(false);
  };

  const handleDeleteScheduleEntry = (userId: string, entryId: string) => {
    const newUserSchedules = config.userSchedules.map(s =>
      s.userId !== userId ? s : { ...s, schedules: s.schedules.filter(e => e.id !== entryId) }
    );
    saveConfig({ ...config, userSchedules: newUserSchedules });
  };

  const toggleDay = (day: number) => {
    setEntryDays(prev => prev.includes(day) ? prev.filter(d => d !== day) : [...prev, day].sort());
  };

  const handleImportSchedules = (importedSchedules: UserSchedule[]) => {
    const newUserSchedules = [...config.userSchedules];
    for (const imported of importedSchedules) {
      const existingIndex = newUserSchedules.findIndex(s => s.userId === imported.userId);
      if (existingIndex >= 0) {
        newUserSchedules[existingIndex] = {
          ...newUserSchedules[existingIndex],
          schedules: [...newUserSchedules[existingIndex].schedules, ...imported.schedules],
        };
      } else {
        newUserSchedules.push(imported);
      }
    }
    saveConfig({ ...config, userSchedules: newUserSchedules });
  };

  const allSchedulesForTimeline = useMemo(
    () => [AI_AGENT_SCHEDULE, ...config.userSchedules],
    [config.userSchedules]
  );

  const activeUsers = localUsers.filter(u => u.active !== false).length;
  const configuredUsers = config.userSchedules.filter(s => s.enabled).length;

  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <Box>
      {/* Header + actions */}
      <Box sx={{ mb: compact ? 2 : 4 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 2 }}>
          {!compact && (
            <Box>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
                <Typography
                  variant="h4"
                  sx={{ fontWeight: 700, color: 'hsl(var(--foreground))', letterSpacing: '-0.02em' }}
                >
                  On-Call Schedule
                </Typography>
                <Chip
                  label="Beta"
                  size="small"
                  sx={{
                    height: 22,
                    fontSize: '0.75rem',
                    fontWeight: 600,
                    bgcolor: 'hsl(var(--primary) / 0.1)',
                    color: 'hsl(var(--primary))',
                    border: '1px solid hsl(var(--primary) / 0.25)',
                    borderRadius: 1,
                    '& .MuiChip-label': { px: 0.75 },
                  }}
                />
              </Box>
              <Typography variant="body1" sx={{ color: 'hsl(var(--muted-foreground))', mt: 1, maxWidth: 560 }}>
                Mark a user On-Call to make them eligible for incident assignment, then expand their row to set weekly availability windows.
              </Typography>
            </Box>
          )}
          <Box sx={{ display: 'flex', gap: 1.5, ml: compact ? 'auto' : undefined }}>
            <Button
              variant="outlined"
              size={compact ? 'small' : 'medium'}
              startIcon={<CalendarIcon />}
              onClick={() => setTimelineDialogOpen(true)}
              sx={{
                height: 36,
                borderColor: 'hsl(var(--border))',
                color: 'hsl(var(--foreground))',
                '&:hover': { borderColor: 'hsl(var(--primary))', bgcolor: 'hsl(var(--primary) / 0.08)' },
              }}
            >
              Schedule View
              <Chip
                label="Beta"
                size="small"
                sx={{
                  ml: 1,
                  height: 18,
                  fontSize: '0.65rem',
                  fontWeight: 600,
                  bgcolor: 'hsl(var(--primary) / 0.1)',
                  color: 'hsl(var(--primary))',
                  border: '1px solid hsl(var(--primary) / 0.25)',
                  borderRadius: 1,
                  '& .MuiChip-label': { px: 0.5 },
                }}
              />
            </Button>
            <Button
              variant="outlined"
              size={compact ? 'small' : 'medium'}
              startIcon={<UploadIcon />}
              onClick={() => setImportDialogOpen(true)}
              sx={{
                height: 36,
                borderColor: 'hsl(var(--border))',
                color: 'hsl(var(--foreground))',
                '&:hover': { borderColor: 'hsl(var(--primary))', bgcolor: 'hsl(var(--primary) / 0.08)' },
              }}
            >
              Import
            </Button>
            <Button
              variant="contained"
              size={compact ? 'small' : 'medium'}
              startIcon={<AddIcon size={16} />}
              onClick={() => setAddUserOpen(true)}
              sx={{
                height: 36,
                bgcolor: 'hsl(var(--primary))',
                color: 'hsl(var(--primary-foreground))',
                fontWeight: 600,
                textTransform: 'none',
                '&:hover': { bgcolor: 'hsl(var(--primary) / 0.9)' },
              }}
            >
              Add User
            </Button>
          </Box>
        </Box>

        {!compact && (
          <Box
            component={motion.div}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            sx={{
              display: 'flex',
              flexWrap: 'wrap',
              gap: { xs: 2, sm: 3 },
              mt: 3,
              color: 'hsl(var(--muted-foreground))',
            }}
          >
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.25 }}>
              <Box sx={{ width: 7, height: 7, borderRadius: '50%', bgcolor: 'hsl(var(--muted-foreground))' }} />
              <Typography variant="body2">
                <Box component="span" sx={{ fontWeight: 600, color: 'hsl(var(--foreground))' }}>{users.length}</Box> total
              </Typography>
            </Box>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.25 }}>
              <Box sx={{ width: 7, height: 7, borderRadius: '50%', bgcolor: 'hsl(var(--foreground))' }} />
              <Typography variant="body2">
                <Box component="span" sx={{ fontWeight: 600, color: 'hsl(var(--foreground))' }}>{activeUsers}</Box> active
              </Typography>
            </Box>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.25 }}>
              <ScheduleIcon size={18} />
              <Typography variant="body2">
                <Box component="span" sx={{ fontWeight: 600, color: 'hsl(var(--foreground))' }}>{configuredUsers}</Box> on-call
              </Typography>
            </Box>
          </Box>
        )}
      </Box>

      {configError && (
        <Alert severity="error" sx={{ mb: 3, borderRadius: 2 }}>{configError}</Alert>
      )}

      {isSaving && (
        <LinearProgress
          sx={{
            mb: 2, borderRadius: 1, bgcolor: 'hsl(var(--muted))',
            '& .MuiLinearProgress-bar': { bgcolor: 'hsl(var(--primary))' },
          }}
        />
      )}

      {loading || configLoading ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 12 }}>
          <CircularProgress sx={{ color: 'hsl(var(--primary))' }} />
        </Box>
      ) : (
        <motion.div variants={containerVariants} initial="hidden" animate="show">
          {/* AI Agent card */}
          <motion.div variants={cardVariants}>
            <Paper sx={{
              p: 3, mb: 3,
              bgcolor: 'hsl(var(--card))',
              border: '1px solid hsl(var(--border))', borderRadius: 2,
              display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              flexWrap: 'wrap', gap: 2,
            }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 2.5 }}>
                <AgentIcon size={44} style={{ borderRadius: 8 }} />
                <Box>
                  <Typography variant="subtitle1" sx={{ fontWeight: 600, color: 'hsl(var(--foreground))' }}>
                    AI Agent
                  </Typography>
                  <Typography variant="body2" sx={{ color: 'hsl(var(--muted-foreground))' }}>
                    24/7 fallback when no human is on-call.
                  </Typography>
                </Box>
              </Box>
              <Typography variant="body2" sx={{ color: 'hsl(var(--muted-foreground))' }}>
                Always active
              </Typography>
            </Paper>
          </motion.div>

          {/* User cards */}
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
            {localUsers.length === 0 ? (
              <Paper sx={{
                p: 6, textAlign: 'center', bgcolor: 'hsl(var(--card))',
                border: '1px solid hsl(var(--border))', borderRadius: 2,
              }}>
                <PersonIcon size={48} style={{ color: 'hsl(var(--muted-foreground))', marginBottom: '16px' }} />
                <Typography sx={{ color: 'hsl(var(--muted-foreground))' }}>No users found</Typography>
              </Paper>
            ) : (
              localUsers.map((user) => {
                const schedule = getUserSchedule(user.id);
                const isExpanded = expandedRows.has(user.id);

                return (
                  <motion.div key={user.id} variants={cardVariants}>
                    <Paper sx={{
                      bgcolor: 'hsl(var(--card))',
                      border: '1px solid hsl(var(--border))',
                      borderRadius: 2, overflow: 'hidden',
                      transition: 'border-color 0.2s',
                      '&:hover': { borderColor: 'hsl(var(--border) / 0.8)' },
                    }}>
                      {/* Main row */}
                      <Box sx={{
                        p: 2.5, display: 'grid',
                        gridTemplateColumns: { xs: '1fr', md: 'auto 1fr auto auto auto auto' },
                        alignItems: 'center', gap: { xs: 2, md: 3 },
                      }}>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                          <Avatar sx={{
                            bgcolor: 'hsl(var(--muted))', color: 'hsl(var(--foreground))',
                            width: 40, height: 40,
                            fontWeight: 600, fontSize: '1rem',
                          }}>
                            {user.username?.charAt(0).toUpperCase() || '?'}
                          </Avatar>
                          <Box>
                            <Typography variant="subtitle1" sx={{ fontWeight: 600, color: 'hsl(var(--foreground))' }}>
                              {user.username}
                            </Typography>
                            <Box sx={{ display: 'flex', gap: 1, mt: 0.5 }}>
                              <UserRoleSelect
                                userId={user.id}
                                username={user.username}
                                currentRole={user.role}
                                onRoleChanged={(newRole) => handleRoleChanged(user.id, newRole)}
                              />
                            </Box>
                          </Box>
                        </Box>

                        <Box sx={{ display: { xs: 'none', md: 'block' } }} />

                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                          <Box sx={{
                            width: 7, height: 7, borderRadius: '50%',
                            bgcolor: user.active !== false ? 'hsl(var(--foreground))' : 'hsl(var(--muted-foreground))',
                          }} />
                          <Typography variant="body2" sx={{ color: 'hsl(var(--muted-foreground))' }}>
                            {user.active !== false ? 'Active' : 'Inactive'}
                          </Typography>
                        </Box>

                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                          {schedule ? (
                            <Button
                              size="small"
                              onClick={() => handleEditEscalation(user.id)}
                              sx={{
                                color: 'hsl(var(--foreground))',
                                textTransform: 'none',
                                fontWeight: 500,
                                minWidth: 0,
                                px: 1,
                                '&:hover': { bgcolor: 'hsl(var(--muted))' },
                              }}
                            >
                              {ESCALATION_LABELS[schedule.escalationLevel]}
                            </Button>
                          ) : (
                            <Button
                              size="small"
                              onClick={() => handleEditEscalation(user.id)}
                              sx={{ color: 'hsl(var(--muted-foreground))', textTransform: 'none' }}
                            >
                              Set level
                            </Button>
                          )}
                        </Box>

                        <FormControlLabel
                          control={
                            <Switch
                              checked={!!schedule?.enabled}
                              onChange={() => handleToggleEnabled(user.id)}
                              disabled={isSaving}
                              size="small"
                            />
                          }
                          label={
                            <Typography variant="body2" sx={{ color: 'hsl(var(--muted-foreground))' }}>
                              {schedule?.enabled ? 'On-Call' : 'Off'}
                            </Typography>
                          }
                          sx={{ ml: 0, mr: 0, gap: 1 }}
                        />

                        <IconButton
                          size="small"
                          onClick={() => toggleRow(user.id)}
                          sx={{
                            color: 'hsl(var(--muted-foreground))',
                            transition: 'transform 0.2s',
                            transform: isExpanded ? 'rotate(180deg)' : 'rotate(0deg)',
                          }}
                        >
                          <ExpandMoreIcon />
                        </IconButton>
                      </Box>

                      {/* Expanded availability windows */}
                      <Collapse in={isExpanded} timeout="auto" unmountOnExit>
                        <Box sx={{
                          p: 3, borderTop: '1px solid hsl(var(--border))',
                        }}>
                          <Box sx={{
                            display: 'flex', justifyContent: 'space-between',
                            alignItems: 'center', mb: 2.5,
                          }}>
                            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
                              <AccessTimeIcon size={18} style={{ color: 'hsl(var(--muted-foreground))' }} />
                              <Typography variant="subtitle2" sx={{ color: 'hsl(var(--foreground))', fontWeight: 600 }}>
                                Availability Windows
                              </Typography>
                            </Box>
                            <Button
                              size="small"
                              startIcon={<AddIcon />}
                              onClick={() => handleAddScheduleEntry(user.id)}
                              sx={{
                                color: 'hsl(var(--foreground))',
                                '&:hover': { bgcolor: 'hsl(var(--muted))' },
                              }}
                            >
                              Add Window
                            </Button>
                          </Box>

                          {!schedule || schedule.schedules.length === 0 ? (
                            <Paper sx={{
                              p: 3, textAlign: 'center', bgcolor: 'hsl(var(--card))',
                              border: '1px dashed hsl(var(--border))', borderRadius: 2,
                            }}>
                              <ScheduleIcon size={32} style={{ color: 'hsl(var(--muted-foreground))', marginBottom: '8px' }} />
                              <Typography variant="body2" sx={{ color: 'hsl(var(--muted-foreground))' }}>
                                No availability windows configured
                              </Typography>
                              <Typography variant="caption" sx={{ color: 'hsl(var(--muted-foreground))' }}>
                                Add windows to enable auto-assignment
                              </Typography>
                            </Paper>
                          ) : (
                            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5 }}>
                              {schedule.schedules.map((entry) => (
                                <Paper key={entry.id} sx={{
                                  p: 2, bgcolor: 'hsl(var(--card))',
                                  border: '1px solid hsl(var(--border))', borderRadius: 1.5,
                                  display: 'flex', alignItems: 'center',
                                  justifyContent: 'space-between', gap: 2, flexWrap: 'wrap',
                                }}>
                                  <Box sx={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
                                    <Box>
                                      <Typography variant="caption" sx={{ color: 'hsl(var(--muted-foreground))', display: 'block', mb: 0.5 }}>
                                        Date Range
                                      </Typography>
                                      <Typography variant="body2" sx={{ color: 'hsl(var(--foreground))', fontWeight: 500 }}>
                                        {new Date(entry.startDate).toLocaleDateString()} – {new Date(entry.endDate).toLocaleDateString()}
                                      </Typography>
                                    </Box>
                                    <Box>
                                      <Typography variant="caption" sx={{ color: 'hsl(var(--muted-foreground))', display: 'block', mb: 0.5 }}>
                                        Hours
                                      </Typography>
                                      <Typography variant="body2" sx={{ color: 'hsl(var(--foreground))', fontWeight: 500 }}>
                                        {entry.startTime} – {entry.endTime}
                                      </Typography>
                                    </Box>
                                    <Box>
                                      <Typography variant="caption" sx={{ color: 'hsl(var(--muted-foreground))', display: 'block', mb: 0.5 }}>
                                        Days
                                      </Typography>
                                      <Box sx={{ display: 'flex', gap: 0.5 }}>
                                        {DAYS_OF_WEEK.map((day, idx) => (
                                          <Box key={day} sx={{
                                            width: 26, height: 24, borderRadius: 0.75,
                                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                                            fontSize: '0.7rem', fontWeight: 500,
                                            border: '1px solid',
                                            borderColor: entry.daysOfWeek.includes(idx) ? 'hsl(var(--foreground))' : 'hsl(var(--border))',
                                            bgcolor: entry.daysOfWeek.includes(idx) ? 'hsl(var(--foreground))' : 'transparent',
                                            color: entry.daysOfWeek.includes(idx) ? 'hsl(var(--background))' : 'hsl(var(--muted-foreground))',
                                          }}>
                                            {day.charAt(0)}
                                          </Box>
                                        ))}
                                      </Box>
                                    </Box>
                                  </Box>
                                  <Box sx={{ display: 'flex', gap: 0.5 }}>
                                    <IconButton
                                      size="small"
                                      onClick={() => handleEditScheduleEntry(user.id, entry)}
                                      sx={{ color: 'hsl(var(--muted-foreground))' }}
                                    >
                                      <EditIcon size={20} />
                                    </IconButton>
                                    <IconButton
                                      size="small"
                                      onClick={() => handleDeleteScheduleEntry(user.id, entry.id)}
                                      sx={{
                                        color: 'hsl(var(--muted-foreground))',
                                        '&:hover': { color: 'hsl(var(--destructive))' },
                                      }}
                                    >
                                      <DeleteIcon size={20} />
                                    </IconButton>
                                  </Box>
                                </Paper>
                              ))}
                            </Box>
                          )}
                        </Box>
                      </Collapse>
                    </Paper>
                  </motion.div>
                );
              })
            )}
          </Box>
        </motion.div>
      )}

      {/* Escalation dialog */}
      <Dialog open={escalationDialogOpen} onClose={() => setEscalationDialogOpen(false)} maxWidth="sm" fullWidth>
        <DialogTitle>Set Escalation Level</DialogTitle>
        <DialogContent>
          <Box sx={{ pt: 2, display: 'flex', flexDirection: 'column', gap: 1 }}>
            {(Object.entries(ESCALATION_LABELS) as [EscalationLevel, string][]).map(([key, label]) => (
              <Paper
                key={key}
                onClick={() => setSelectedLevel(key)}
                sx={{
                  p: 2, cursor: 'pointer',
                  border: '1px solid hsl(var(--border))',
                  borderRadius: 2,
                  bgcolor: selectedLevel === key ? 'hsl(var(--muted))' : 'transparent',
                  display: 'flex', alignItems: 'center', gap: 2,
                  transition: 'all 0.2s',
                  '&:hover': { bgcolor: 'hsl(var(--muted))' },
                }}
              >
                <Box>
                  <Typography variant="subtitle2" sx={{ color: 'hsl(var(--foreground))', fontWeight: 500 }}>
                    {label}
                  </Typography>
                  <Typography variant="caption" sx={{ color: 'hsl(var(--muted-foreground))' }}>
                    {ESCALATION_DESCRIPTIONS[key]}
                  </Typography>
                </Box>
              </Paper>
            ))}
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setEscalationDialogOpen(false)}>Cancel</Button>
          <Button onClick={handleSaveEscalation} variant="contained" disabled={isSaving}>
            {isSaving ? <CircularProgress size={20} /> : 'Save'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Schedule entry dialog */}
      <Dialog open={scheduleDialogOpen} onClose={() => setScheduleDialogOpen(false)} maxWidth="sm" fullWidth>
        <DialogTitle>{editingEntry ? 'Edit Availability Window' : 'Add Availability Window'}</DialogTitle>
        <DialogContent>
          <Stack spacing={3} sx={{ mt: 2 }}>
            <Box display="flex" gap={2}>
              <TextField label="Start Date" type="date" value={entryStartDate}
                onChange={(e) => setEntryStartDate(e.target.value)} InputLabelProps={{ shrink: true }} fullWidth />
              <TextField label="End Date" type="date" value={entryEndDate}
                onChange={(e) => setEntryEndDate(e.target.value)} InputLabelProps={{ shrink: true }} fullWidth />
            </Box>
            <Box display="flex" gap={2}>
              <TextField label="Start Time" type="time" value={entryStartTime}
                onChange={(e) => setEntryStartTime(e.target.value)} InputLabelProps={{ shrink: true }} fullWidth />
              <TextField label="End Time" type="time" value={entryEndTime}
                onChange={(e) => setEntryEndTime(e.target.value)} InputLabelProps={{ shrink: true }} fullWidth />
            </Box>
            <Box>
              <Typography variant="body2" sx={{ mb: 1.5, color: 'hsl(var(--foreground))' }}>Days of Week</Typography>
              <Box display="flex" gap={1} flexWrap="wrap">
                {DAYS_OF_WEEK.map((day, index) => (
                  <Chip
                    key={day}
                    label={day}
                    variant="outlined"
                    onClick={() => toggleDay(index)}
                    sx={{
                      borderColor: entryDays.includes(index) ? 'hsl(var(--foreground))' : 'hsl(var(--border))',
                      bgcolor: entryDays.includes(index) ? 'hsl(var(--foreground))' : 'transparent',
                      color: entryDays.includes(index) ? 'hsl(var(--background))' : 'hsl(var(--muted-foreground))',
                      fontWeight: 500,
                      '&:hover': {
                        bgcolor: entryDays.includes(index) ? 'hsl(var(--foreground))' : 'hsl(var(--muted))',
                      },
                    }}
                  />
                ))}
              </Box>
            </Box>
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setScheduleDialogOpen(false)}>Cancel</Button>
          <Button
            onClick={handleSaveScheduleEntry}
            variant="contained"
            disabled={!entryStartDate || !entryEndDate || entryDays.length === 0 || isSaving}
          >
            {isSaving ? <CircularProgress size={20} /> : 'Save'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Weekly timeline preview */}
      <Dialog
        open={timelineDialogOpen}
        onClose={() => setTimelineDialogOpen(false)}
        maxWidth="lg" fullWidth
        PaperProps={{
          sx: { backgroundColor: 'background.paper', border: '1px solid', borderColor: 'divider' },
        }}
      >
        <DialogTitle sx={{ color: 'hsl(var(--foreground))', display: 'flex', alignItems: 'center', gap: 1.5 }}>
          On-Call Schedule
          <Chip
            label="Beta"
            size="small"
            sx={{
              height: 20,
              fontSize: '0.7rem',
              fontWeight: 600,
              bgcolor: 'hsl(var(--primary) / 0.1)',
              color: 'hsl(var(--primary))',
              border: '1px solid hsl(var(--primary) / 0.25)',
              borderRadius: 1,
              '& .MuiChip-label': { px: 0.75 },
            }}
          />
        </DialogTitle>
        <DialogContent>
          <WeeklyScheduleTimeline userSchedules={allSchedulesForTimeline} />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setTimelineDialogOpen(false)}>Close</Button>
        </DialogActions>
      </Dialog>

      <ScheduleImportDialog
        open={importDialogOpen}
        onClose={() => setImportDialogOpen(false)}
        existingUsers={localUsers}
        onImport={handleImportSchedules}
      />

      <AddUserDialog
        open={addUserOpen}
        onClose={() => setAddUserOpen(false)}
        onUserAdded={onRefreshUsers}
      />
    </Box>
  );
};

export default OnCallScheduleManager;
