/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CondRouteImport } from './routes/_cond'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as AdminsetupRouteImport } from './routes/adminsetup'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MobileLoginRouteImport } from './routes/mobile-login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ShuffleCoreRouteImport } from './routes/shuffle-core'
import { Route as ShuffleCoreDemoRouteImport } from './routes/shuffle-core-demo'
import { Route as ShuffleMcpDemoRouteImport } from './routes/shuffle-mcp-demo'
import { Route as ShuffleMcpsRouteImport } from './routes/shuffle-mcps'
import { Route as CondSearchRouteImport } from './routes/_cond.search'
import { Route as DashAgentRouteImport } from './routes/_dash.agent'
import { Route as DashDashboardRouteImport } from './routes/_dash.dashboard'
import { Route as DashDashboardViewRouteImport } from './routes/_dash.dashboard-view'
import { Route as DashOrganizationsRouteImport } from './routes/_dash.organizations'
import { Route as DashPreferencesRouteImport } from './routes/_dash.preferences'
import { Route as DashSettingsRouteImport } from './routes/_dash.settings'
import { Route as DashTemplatesRouteImport } from './routes/_dash.templates'
import { Route as DashUsersRouteImport } from './routes/_dash.users'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesNameRouteImport } from './routes/articles.$name'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogNameRouteImport } from './routes/blog.$name'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as Oauth2AuthorizeRouteImport } from './routes/oauth2.authorize'
import { Route as PasswordresetKeyRouteImport } from './routes/passwordreset.$key'
import { Route as CondAppsAppnameRouteImport } from './routes/_cond.apps.$appname'
import { Route as CondFormsIndexRouteImport } from './routes/_cond.forms.index'
import { Route as CondFormsIdRouteImport } from './routes/_cond.forms.$id'
import { Route as CondUsecasesIndexRouteImport } from './routes/_cond.usecases.index'
import { Route as CondVulnerabilitiesIndexRouteImport } from './routes/_cond.vulnerabilities.index'
import { Route as CondVulnerabilitiesSplatRouteImport } from './routes/_cond.vulnerabilities.$'
import { Route as DashAdminIndexRouteImport } from './routes/_dash.admin.index'
import { Route as DashAdminDatastoreRouteImport } from './routes/_dash.admin.datastore'
import { Route as DashAdminLocationsRouteImport } from './routes/_dash.admin.locations'
import { Route as DashAdminPreferencesRouteImport } from './routes/_dash.admin.preferences'
import { Route as DashAdminRuntimeLocationsRouteImport } from './routes/_dash.admin.runtime-locations'
import { Route as DashAdminTenantsRouteImport } from './routes/_dash.admin.tenants'
import { Route as DashAdminUsersRouteImport } from './routes/_dash.admin.users'
import { Route as DashAgentsIndexRouteImport } from './routes/_dash.agents.index'
import { Route as DashAgentsExecutionIdRouteImport } from './routes/_dash.agents.$executionId'
import { Route as DashAlertsIndexRouteImport } from './routes/_dash.alerts.index'
import { Route as DashAlertsIdRouteImport } from './routes/_dash.alerts.$id'
import { Route as DashAssetsIndexRouteImport } from './routes/_dash.assets.index'
import { Route as DashAssetsTabRouteImport } from './routes/_dash.assets.$tab'
import { Route as DashCasesIndexRouteImport } from './routes/_dash.cases.index'
import { Route as DashCasesIdRouteImport } from './routes/_dash.cases.$id'
import { Route as DashDetectionIndexRouteImport } from './routes/_dash.detection.index'
import { Route as DashDetectionIocTypesRouteImport } from './routes/_dash.detection.ioc-types'
import { Route as DashDetectionMitreRouteImport } from './routes/_dash.detection.mitre'
import { Route as DashDetectionPipelinesRouteImport } from './routes/_dash.detection.pipelines'
import { Route as DashDetectionSigmaRouteImport } from './routes/_dash.detection.sigma'
import { Route as DashDetectionThreatFeedsRouteImport } from './routes/_dash.detection.threat-feeds'
import { Route as DashIncidentsSimpleIndexRouteImport } from './routes/_dash.incidents-simple.index'
import { Route as DashIncidentsSimpleIdRouteImport } from './routes/_dash.incidents-simple.$id'
import { Route as DashIncidentsIndexRouteImport } from './routes/_dash.incidents.index'
import { Route as DashIncidentsIdRouteImport } from './routes/_dash.incidents.$id'
import { Route as DashIncidentsCustomFieldsRouteImport } from './routes/_dash.incidents.custom-fields'
import { Route as DashIncidentsIocTypesRouteImport } from './routes/_dash.incidents.ioc-types'
import { Route as DashIncidentsObservablesRouteImport } from './routes/_dash.incidents.observables'
import { Route as DashIncidentsResponseActionsRouteImport } from './routes/_dash.incidents.response-actions'
import { Route as DashIncidentsThreatFeedsRouteImport } from './routes/_dash.incidents.threat-feeds'
import { Route as DashInfrastructureIndexRouteImport } from './routes/_dash.infrastructure.index'
import { Route as DashJobsIndexRouteImport } from './routes/_dash.jobs.index'
import { Route as DashJobsIdRouteImport } from './routes/_dash.jobs.$id'
import { Route as DashMonitorsIndexRouteImport } from './routes/_dash.monitors.index'
import { Route as DashMonitorsResponseRouteImport } from './routes/_dash.monitors.response'
import { Route as DashMonitorsTerminalRouteImport } from './routes/_dash.monitors.terminal'
import { Route as DashPackagesSplatRouteImport } from './routes/_dash.packages.$'
import { Route as DashSoftwareSplatRouteImport } from './routes/_dash.software.$'
import { Route as DashTicketsIndexRouteImport } from './routes/_dash.tickets.index'
import { Route as DashTicketsIdRouteImport } from './routes/_dash.tickets.$id'
import { Route as DashWorkflowsIndexRouteImport } from './routes/_dash.workflows.index'
import { Route as DashWorkflowsIdRouteImport } from './routes/_dash.workflows.$id'
import { Route as DashWorkflowsDebugRouteImport } from './routes/_dash.workflows.debug'
import { Route as OnboardingOnboardingIndexRouteImport } from './routes/_onboarding.onboarding.index'
import { Route as OnboardingOnboardingAuthenticateRouteImport } from './routes/_onboarding.onboarding.authenticate'
import { Route as OnboardingOnboardingAutomateRouteImport } from './routes/_onboarding.onboarding.automate'
import { Route as OnboardingOnboardingProductRouteImport } from './routes/_onboarding.onboarding.product'
import { Route as OnboardingOnboardingSourcesRouteImport } from './routes/_onboarding.onboarding.sources'
import { Route as OnboardingOnboardingWelcomeRouteImport } from './routes/_onboarding.onboarding.welcome'
import { Route as LoginUrlMfaSetupRouteImport } from './routes/login.$url.mfa-setup'
import { Route as CondUsecasesFlowIdIndexRouteImport } from './routes/_cond.usecases.$flowId.index'
import { Route as CondUsecasesFlowIdDetailsRouteImport } from './routes/_cond.usecases.$flowId.details'
import { Route as DashInfrastructureFlowsFlowIdRouteImport } from './routes/_dash.infrastructure.flows.$flowId'
import { Route as DashMonitorsIdIndexRouteImport } from './routes/_dash.monitors.$id.index'
import { Route as DashMonitorsIdTerminalRouteImport } from './routes/_dash.monitors.$id.terminal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CondRoute = CondRouteImport.update({
  id: '/_cond',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsetupRoute = AdminsetupRouteImport.update({
  id: '/adminsetup',
  path: '/adminsetup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileLoginRoute = MobileLoginRouteImport.update({
  id: '/mobile-login',
  path: '/mobile-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuffleCoreRoute = ShuffleCoreRouteImport.update({
  id: '/shuffle-core',
  path: '/shuffle-core',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuffleCoreDemoRoute = ShuffleCoreDemoRouteImport.update({
  id: '/shuffle-core-demo',
  path: '/shuffle-core-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuffleMcpDemoRoute = ShuffleMcpDemoRouteImport.update({
  id: '/shuffle-mcp-demo',
  path: '/shuffle-mcp-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuffleMcpsRoute = ShuffleMcpsRouteImport.update({
  id: '/shuffle-mcps',
  path: '/shuffle-mcps',
  getParentRoute: () => rootRouteImport,
} as any)
const CondSearchRoute = CondSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => CondRoute,
} as any)
const DashAgentRoute = DashAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardViewRoute = DashDashboardViewRouteImport.update({
  id: '/dashboard-view',
  path: '/dashboard-view',
  getParentRoute: () => DashRoute,
} as any)
const DashOrganizationsRoute = DashOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => DashRoute,
} as any)
const DashPreferencesRoute = DashPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashTemplatesRoute = DashTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashRoute,
} as any)
const DashUsersRoute = DashUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNameRoute = ArticlesNameRouteImport.update({
  id: '/articles/$name',
  path: '/articles/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNameRoute = BlogNameRouteImport.update({
  id: '/blog/$name',
  path: '/blog/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2AuthorizeRoute = Oauth2AuthorizeRouteImport.update({
  id: '/oauth2/authorize',
  path: '/oauth2/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordresetKeyRoute = PasswordresetKeyRouteImport.update({
  id: '/passwordreset/$key',
  path: '/passwordreset/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const CondAppsAppnameRoute = CondAppsAppnameRouteImport.update({
  id: '/apps/$appname',
  path: '/apps/$appname',
  getParentRoute: () => CondRoute,
} as any)
const CondFormsIndexRoute = CondFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => CondRoute,
} as any)
const CondFormsIdRoute = CondFormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => CondRoute,
} as any)
const CondUsecasesIndexRoute = CondUsecasesIndexRouteImport.update({
  id: '/usecases/',
  path: '/usecases/',
  getParentRoute: () => CondRoute,
} as any)
const CondVulnerabilitiesIndexRoute =
  CondVulnerabilitiesIndexRouteImport.update({
    id: '/vulnerabilities/',
    path: '/vulnerabilities/',
    getParentRoute: () => CondRoute,
  } as any)
const CondVulnerabilitiesSplatRoute =
  CondVulnerabilitiesSplatRouteImport.update({
    id: '/vulnerabilities/$',
    path: '/vulnerabilities/$',
    getParentRoute: () => CondRoute,
  } as any)
const DashAdminIndexRoute = DashAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashRoute,
} as any)
const DashAdminDatastoreRoute = DashAdminDatastoreRouteImport.update({
  id: '/admin/datastore',
  path: '/admin/datastore',
  getParentRoute: () => DashRoute,
} as any)
const DashAdminLocationsRoute = DashAdminLocationsRouteImport.update({
  id: '/admin/locations',
  path: '/admin/locations',
  getParentRoute: () => DashRoute,
} as any)
const DashAdminPreferencesRoute = DashAdminPreferencesRouteImport.update({
  id: '/admin/preferences',
  path: '/admin/preferences',
  getParentRoute: () => DashRoute,
} as any)
const DashAdminRuntimeLocationsRoute =
  DashAdminRuntimeLocationsRouteImport.update({
    id: '/admin/runtime-locations',
    path: '/admin/runtime-locations',
    getParentRoute: () => DashRoute,
  } as any)
const DashAdminTenantsRoute = DashAdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => DashRoute,
} as any)
const DashAdminUsersRoute = DashAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashRoute,
} as any)
const DashAgentsIndexRoute = DashAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => DashRoute,
} as any)
const DashAgentsExecutionIdRoute = DashAgentsExecutionIdRouteImport.update({
  id: '/agents/$executionId',
  path: '/agents/$executionId',
  getParentRoute: () => DashRoute,
} as any)
const DashAlertsIndexRoute = DashAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => DashRoute,
} as any)
const DashAlertsIdRoute = DashAlertsIdRouteImport.update({
  id: '/alerts/$id',
  path: '/alerts/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashAssetsIndexRoute = DashAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => DashRoute,
} as any)
const DashAssetsTabRoute = DashAssetsTabRouteImport.update({
  id: '/assets/$tab',
  path: '/assets/$tab',
  getParentRoute: () => DashRoute,
} as any)
const DashCasesIndexRoute = DashCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => DashRoute,
} as any)
const DashCasesIdRoute = DashCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashDetectionIndexRoute = DashDetectionIndexRouteImport.update({
  id: '/detection/',
  path: '/detection/',
  getParentRoute: () => DashRoute,
} as any)
const DashDetectionIocTypesRoute = DashDetectionIocTypesRouteImport.update({
  id: '/detection/ioc-types',
  path: '/detection/ioc-types',
  getParentRoute: () => DashRoute,
} as any)
const DashDetectionMitreRoute = DashDetectionMitreRouteImport.update({
  id: '/detection/mitre',
  path: '/detection/mitre',
  getParentRoute: () => DashRoute,
} as any)
const DashDetectionPipelinesRoute = DashDetectionPipelinesRouteImport.update({
  id: '/detection/pipelines',
  path: '/detection/pipelines',
  getParentRoute: () => DashRoute,
} as any)
const DashDetectionSigmaRoute = DashDetectionSigmaRouteImport.update({
  id: '/detection/sigma',
  path: '/detection/sigma',
  getParentRoute: () => DashRoute,
} as any)
const DashDetectionThreatFeedsRoute =
  DashDetectionThreatFeedsRouteImport.update({
    id: '/detection/threat-feeds',
    path: '/detection/threat-feeds',
    getParentRoute: () => DashRoute,
  } as any)
const DashIncidentsSimpleIndexRoute =
  DashIncidentsSimpleIndexRouteImport.update({
    id: '/incidents-simple/',
    path: '/incidents-simple/',
    getParentRoute: () => DashRoute,
  } as any)
const DashIncidentsSimpleIdRoute = DashIncidentsSimpleIdRouteImport.update({
  id: '/incidents-simple/$id',
  path: '/incidents-simple/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashIncidentsIndexRoute = DashIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => DashRoute,
} as any)
const DashIncidentsIdRoute = DashIncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashIncidentsCustomFieldsRoute =
  DashIncidentsCustomFieldsRouteImport.update({
    id: '/incidents/custom-fields',
    path: '/incidents/custom-fields',
    getParentRoute: () => DashRoute,
  } as any)
const DashIncidentsIocTypesRoute = DashIncidentsIocTypesRouteImport.update({
  id: '/incidents/ioc-types',
  path: '/incidents/ioc-types',
  getParentRoute: () => DashRoute,
} as any)
const DashIncidentsObservablesRoute =
  DashIncidentsObservablesRouteImport.update({
    id: '/incidents/observables',
    path: '/incidents/observables',
    getParentRoute: () => DashRoute,
  } as any)
const DashIncidentsResponseActionsRoute =
  DashIncidentsResponseActionsRouteImport.update({
    id: '/incidents/response-actions',
    path: '/incidents/response-actions',
    getParentRoute: () => DashRoute,
  } as any)
const DashIncidentsThreatFeedsRoute =
  DashIncidentsThreatFeedsRouteImport.update({
    id: '/incidents/threat-feeds',
    path: '/incidents/threat-feeds',
    getParentRoute: () => DashRoute,
  } as any)
const DashInfrastructureIndexRoute = DashInfrastructureIndexRouteImport.update({
  id: '/infrastructure/',
  path: '/infrastructure/',
  getParentRoute: () => DashRoute,
} as any)
const DashJobsIndexRoute = DashJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => DashRoute,
} as any)
const DashJobsIdRoute = DashJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashMonitorsIndexRoute = DashMonitorsIndexRouteImport.update({
  id: '/monitors/',
  path: '/monitors/',
  getParentRoute: () => DashRoute,
} as any)
const DashMonitorsResponseRoute = DashMonitorsResponseRouteImport.update({
  id: '/monitors/response',
  path: '/monitors/response',
  getParentRoute: () => DashRoute,
} as any)
const DashMonitorsTerminalRoute = DashMonitorsTerminalRouteImport.update({
  id: '/monitors/terminal',
  path: '/monitors/terminal',
  getParentRoute: () => DashRoute,
} as any)
const DashPackagesSplatRoute = DashPackagesSplatRouteImport.update({
  id: '/packages/$',
  path: '/packages/$',
  getParentRoute: () => DashRoute,
} as any)
const DashSoftwareSplatRoute = DashSoftwareSplatRouteImport.update({
  id: '/software/$',
  path: '/software/$',
  getParentRoute: () => DashRoute,
} as any)
const DashTicketsIndexRoute = DashTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => DashRoute,
} as any)
const DashTicketsIdRoute = DashTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashWorkflowsIndexRoute = DashWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => DashRoute,
} as any)
const DashWorkflowsIdRoute = DashWorkflowsIdRouteImport.update({
  id: '/workflows/$id',
  path: '/workflows/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashWorkflowsDebugRoute = DashWorkflowsDebugRouteImport.update({
  id: '/workflows/debug',
  path: '/workflows/debug',
  getParentRoute: () => DashRoute,
} as any)
const OnboardingOnboardingIndexRoute =
  OnboardingOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => OnboardingRoute,
  } as any)
const OnboardingOnboardingAuthenticateRoute =
  OnboardingOnboardingAuthenticateRouteImport.update({
    id: '/onboarding/authenticate',
    path: '/onboarding/authenticate',
    getParentRoute: () => OnboardingRoute,
  } as any)
const OnboardingOnboardingAutomateRoute =
  OnboardingOnboardingAutomateRouteImport.update({
    id: '/onboarding/automate',
    path: '/onboarding/automate',
    getParentRoute: () => OnboardingRoute,
  } as any)
const OnboardingOnboardingProductRoute =
  OnboardingOnboardingProductRouteImport.update({
    id: '/onboarding/product',
    path: '/onboarding/product',
    getParentRoute: () => OnboardingRoute,
  } as any)
const OnboardingOnboardingSourcesRoute =
  OnboardingOnboardingSourcesRouteImport.update({
    id: '/onboarding/sources',
    path: '/onboarding/sources',
    getParentRoute: () => OnboardingRoute,
  } as any)
const OnboardingOnboardingWelcomeRoute =
  OnboardingOnboardingWelcomeRouteImport.update({
    id: '/onboarding/welcome',
    path: '/onboarding/welcome',
    getParentRoute: () => OnboardingRoute,
  } as any)
const LoginUrlMfaSetupRoute = LoginUrlMfaSetupRouteImport.update({
  id: '/$url/mfa-setup',
  path: '/$url/mfa-setup',
  getParentRoute: () => LoginRoute,
} as any)
const CondUsecasesFlowIdIndexRoute = CondUsecasesFlowIdIndexRouteImport.update({
  id: '/usecases/$flowId/',
  path: '/usecases/$flowId/',
  getParentRoute: () => CondRoute,
} as any)
const CondUsecasesFlowIdDetailsRoute =
  CondUsecasesFlowIdDetailsRouteImport.update({
    id: '/usecases/$flowId/details',
    path: '/usecases/$flowId/details',
    getParentRoute: () => CondRoute,
  } as any)
const DashInfrastructureFlowsFlowIdRoute =
  DashInfrastructureFlowsFlowIdRouteImport.update({
    id: '/infrastructure/flows/$flowId',
    path: '/infrastructure/flows/$flowId',
    getParentRoute: () => DashRoute,
  } as any)
const DashMonitorsIdIndexRoute = DashMonitorsIdIndexRouteImport.update({
  id: '/monitors/$id/',
  path: '/monitors/$id/',
  getParentRoute: () => DashRoute,
} as any)
const DashMonitorsIdTerminalRoute = DashMonitorsIdTerminalRouteImport.update({
  id: '/monitors/$id/terminal',
  path: '/monitors/$id/terminal',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminsetup': typeof AdminsetupRoute
  '/apps': typeof AppsRoute
  '/login': typeof LoginRouteWithChildren
  '/mobile-login': typeof MobileLoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/shuffle-core': typeof ShuffleCoreRoute
  '/shuffle-core-demo': typeof ShuffleCoreDemoRoute
  '/shuffle-mcp-demo': typeof ShuffleMcpDemoRoute
  '/shuffle-mcps': typeof ShuffleMcpsRoute
  '/search': typeof CondSearchRoute
  '/agent': typeof DashAgentRoute
  '/dashboard': typeof DashDashboardRoute
  '/dashboard-view': typeof DashDashboardViewRoute
  '/organizations': typeof DashOrganizationsRoute
  '/preferences': typeof DashPreferencesRoute
  '/settings': typeof DashSettingsRoute
  '/templates': typeof DashTemplatesRoute
  '/users': typeof DashUsersRoute
  '/articles/$name': typeof ArticlesNameRoute
  '/blog/$name': typeof BlogNameRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/oauth2/authorize': typeof Oauth2AuthorizeRoute
  '/passwordreset/$key': typeof PasswordresetKeyRoute
  '/articles/': typeof ArticlesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/apps/$appname': typeof CondAppsAppnameRoute
  '/forms/$id': typeof CondFormsIdRoute
  '/vulnerabilities/$': typeof CondVulnerabilitiesSplatRoute
  '/admin/datastore': typeof DashAdminDatastoreRoute
  '/admin/locations': typeof DashAdminLocationsRoute
  '/admin/preferences': typeof DashAdminPreferencesRoute
  '/admin/runtime-locations': typeof DashAdminRuntimeLocationsRoute
  '/admin/tenants': typeof DashAdminTenantsRoute
  '/admin/users': typeof DashAdminUsersRoute
  '/agents/$executionId': typeof DashAgentsExecutionIdRoute
  '/alerts/$id': typeof DashAlertsIdRoute
  '/assets/$tab': typeof DashAssetsTabRoute
  '/cases/$id': typeof DashCasesIdRoute
  '/detection/ioc-types': typeof DashDetectionIocTypesRoute
  '/detection/mitre': typeof DashDetectionMitreRoute
  '/detection/pipelines': typeof DashDetectionPipelinesRoute
  '/detection/sigma': typeof DashDetectionSigmaRoute
  '/detection/threat-feeds': typeof DashDetectionThreatFeedsRoute
  '/incidents-simple/$id': typeof DashIncidentsSimpleIdRoute
  '/incidents/$id': typeof DashIncidentsIdRoute
  '/incidents/custom-fields': typeof DashIncidentsCustomFieldsRoute
  '/incidents/ioc-types': typeof DashIncidentsIocTypesRoute
  '/incidents/observables': typeof DashIncidentsObservablesRoute
  '/incidents/response-actions': typeof DashIncidentsResponseActionsRoute
  '/incidents/threat-feeds': typeof DashIncidentsThreatFeedsRoute
  '/jobs/$id': typeof DashJobsIdRoute
  '/monitors/response': typeof DashMonitorsResponseRoute
  '/monitors/terminal': typeof DashMonitorsTerminalRoute
  '/packages/$': typeof DashPackagesSplatRoute
  '/software/$': typeof DashSoftwareSplatRoute
  '/tickets/$id': typeof DashTicketsIdRoute
  '/workflows/$id': typeof DashWorkflowsIdRoute
  '/workflows/debug': typeof DashWorkflowsDebugRoute
  '/onboarding/authenticate': typeof OnboardingOnboardingAuthenticateRoute
  '/onboarding/automate': typeof OnboardingOnboardingAutomateRoute
  '/onboarding/product': typeof OnboardingOnboardingProductRoute
  '/onboarding/sources': typeof OnboardingOnboardingSourcesRoute
  '/onboarding/welcome': typeof OnboardingOnboardingWelcomeRoute
  '/login/$url/mfa-setup': typeof LoginUrlMfaSetupRoute
  '/forms/': typeof CondFormsIndexRoute
  '/usecases/': typeof CondUsecasesIndexRoute
  '/vulnerabilities/': typeof CondVulnerabilitiesIndexRoute
  '/admin/': typeof DashAdminIndexRoute
  '/agents/': typeof DashAgentsIndexRoute
  '/alerts/': typeof DashAlertsIndexRoute
  '/assets/': typeof DashAssetsIndexRoute
  '/cases/': typeof DashCasesIndexRoute
  '/detection/': typeof DashDetectionIndexRoute
  '/incidents-simple/': typeof DashIncidentsSimpleIndexRoute
  '/incidents/': typeof DashIncidentsIndexRoute
  '/infrastructure/': typeof DashInfrastructureIndexRoute
  '/jobs/': typeof DashJobsIndexRoute
  '/monitors/': typeof DashMonitorsIndexRoute
  '/tickets/': typeof DashTicketsIndexRoute
  '/workflows/': typeof DashWorkflowsIndexRoute
  '/onboarding/': typeof OnboardingOnboardingIndexRoute
  '/usecases/$flowId/details': typeof CondUsecasesFlowIdDetailsRoute
  '/infrastructure/flows/$flowId': typeof DashInfrastructureFlowsFlowIdRoute
  '/monitors/$id/terminal': typeof DashMonitorsIdTerminalRoute
  '/usecases/$flowId/': typeof CondUsecasesFlowIdIndexRoute
  '/monitors/$id/': typeof DashMonitorsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminsetup': typeof AdminsetupRoute
  '/apps': typeof AppsRoute
  '/login': typeof LoginRouteWithChildren
  '/mobile-login': typeof MobileLoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/shuffle-core': typeof ShuffleCoreRoute
  '/shuffle-core-demo': typeof ShuffleCoreDemoRoute
  '/shuffle-mcp-demo': typeof ShuffleMcpDemoRoute
  '/shuffle-mcps': typeof ShuffleMcpsRoute
  '/search': typeof CondSearchRoute
  '/agent': typeof DashAgentRoute
  '/dashboard': typeof DashDashboardRoute
  '/dashboard-view': typeof DashDashboardViewRoute
  '/organizations': typeof DashOrganizationsRoute
  '/preferences': typeof DashPreferencesRoute
  '/settings': typeof DashSettingsRoute
  '/templates': typeof DashTemplatesRoute
  '/users': typeof DashUsersRoute
  '/articles/$name': typeof ArticlesNameRoute
  '/blog/$name': typeof BlogNameRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/oauth2/authorize': typeof Oauth2AuthorizeRoute
  '/passwordreset/$key': typeof PasswordresetKeyRoute
  '/articles': typeof ArticlesIndexRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/legal': typeof LegalIndexRoute
  '/apps/$appname': typeof CondAppsAppnameRoute
  '/forms/$id': typeof CondFormsIdRoute
  '/vulnerabilities/$': typeof CondVulnerabilitiesSplatRoute
  '/admin/datastore': typeof DashAdminDatastoreRoute
  '/admin/locations': typeof DashAdminLocationsRoute
  '/admin/preferences': typeof DashAdminPreferencesRoute
  '/admin/runtime-locations': typeof DashAdminRuntimeLocationsRoute
  '/admin/tenants': typeof DashAdminTenantsRoute
  '/admin/users': typeof DashAdminUsersRoute
  '/agents/$executionId': typeof DashAgentsExecutionIdRoute
  '/alerts/$id': typeof DashAlertsIdRoute
  '/assets/$tab': typeof DashAssetsTabRoute
  '/cases/$id': typeof DashCasesIdRoute
  '/detection/ioc-types': typeof DashDetectionIocTypesRoute
  '/detection/mitre': typeof DashDetectionMitreRoute
  '/detection/pipelines': typeof DashDetectionPipelinesRoute
  '/detection/sigma': typeof DashDetectionSigmaRoute
  '/detection/threat-feeds': typeof DashDetectionThreatFeedsRoute
  '/incidents-simple/$id': typeof DashIncidentsSimpleIdRoute
  '/incidents/$id': typeof DashIncidentsIdRoute
  '/incidents/custom-fields': typeof DashIncidentsCustomFieldsRoute
  '/incidents/ioc-types': typeof DashIncidentsIocTypesRoute
  '/incidents/observables': typeof DashIncidentsObservablesRoute
  '/incidents/response-actions': typeof DashIncidentsResponseActionsRoute
  '/incidents/threat-feeds': typeof DashIncidentsThreatFeedsRoute
  '/jobs/$id': typeof DashJobsIdRoute
  '/monitors/response': typeof DashMonitorsResponseRoute
  '/monitors/terminal': typeof DashMonitorsTerminalRoute
  '/packages/$': typeof DashPackagesSplatRoute
  '/software/$': typeof DashSoftwareSplatRoute
  '/tickets/$id': typeof DashTicketsIdRoute
  '/workflows/$id': typeof DashWorkflowsIdRoute
  '/workflows/debug': typeof DashWorkflowsDebugRoute
  '/onboarding/authenticate': typeof OnboardingOnboardingAuthenticateRoute
  '/onboarding/automate': typeof OnboardingOnboardingAutomateRoute
  '/onboarding/product': typeof OnboardingOnboardingProductRoute
  '/onboarding/sources': typeof OnboardingOnboardingSourcesRoute
  '/onboarding/welcome': typeof OnboardingOnboardingWelcomeRoute
  '/login/$url/mfa-setup': typeof LoginUrlMfaSetupRoute
  '/forms': typeof CondFormsIndexRoute
  '/usecases': typeof CondUsecasesIndexRoute
  '/vulnerabilities': typeof CondVulnerabilitiesIndexRoute
  '/admin': typeof DashAdminIndexRoute
  '/agents': typeof DashAgentsIndexRoute
  '/alerts': typeof DashAlertsIndexRoute
  '/assets': typeof DashAssetsIndexRoute
  '/cases': typeof DashCasesIndexRoute
  '/detection': typeof DashDetectionIndexRoute
  '/incidents-simple': typeof DashIncidentsSimpleIndexRoute
  '/incidents': typeof DashIncidentsIndexRoute
  '/infrastructure': typeof DashInfrastructureIndexRoute
  '/jobs': typeof DashJobsIndexRoute
  '/monitors': typeof DashMonitorsIndexRoute
  '/tickets': typeof DashTicketsIndexRoute
  '/workflows': typeof DashWorkflowsIndexRoute
  '/onboarding': typeof OnboardingOnboardingIndexRoute
  '/usecases/$flowId/details': typeof CondUsecasesFlowIdDetailsRoute
  '/infrastructure/flows/$flowId': typeof DashInfrastructureFlowsFlowIdRoute
  '/monitors/$id/terminal': typeof DashMonitorsIdTerminalRoute
  '/usecases/$flowId': typeof CondUsecasesFlowIdIndexRoute
  '/monitors/$id': typeof DashMonitorsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_cond': typeof CondRouteWithChildren
  '/_dash': typeof DashRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/adminsetup': typeof AdminsetupRoute
  '/apps': typeof AppsRoute
  '/login': typeof LoginRouteWithChildren
  '/mobile-login': typeof MobileLoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/shuffle-core': typeof ShuffleCoreRoute
  '/shuffle-core-demo': typeof ShuffleCoreDemoRoute
  '/shuffle-mcp-demo': typeof ShuffleMcpDemoRoute
  '/shuffle-mcps': typeof ShuffleMcpsRoute
  '/_cond/search': typeof CondSearchRoute
  '/_dash/agent': typeof DashAgentRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/dashboard-view': typeof DashDashboardViewRoute
  '/_dash/organizations': typeof DashOrganizationsRoute
  '/_dash/preferences': typeof DashPreferencesRoute
  '/_dash/settings': typeof DashSettingsRoute
  '/_dash/templates': typeof DashTemplatesRoute
  '/_dash/users': typeof DashUsersRoute
  '/articles/$name': typeof ArticlesNameRoute
  '/blog/$name': typeof BlogNameRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/oauth2/authorize': typeof Oauth2AuthorizeRoute
  '/passwordreset/$key': typeof PasswordresetKeyRoute
  '/articles/': typeof ArticlesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/_cond/apps/$appname': typeof CondAppsAppnameRoute
  '/_cond/forms/$id': typeof CondFormsIdRoute
  '/_cond/vulnerabilities/$': typeof CondVulnerabilitiesSplatRoute
  '/_dash/admin/datastore': typeof DashAdminDatastoreRoute
  '/_dash/admin/locations': typeof DashAdminLocationsRoute
  '/_dash/admin/preferences': typeof DashAdminPreferencesRoute
  '/_dash/admin/runtime-locations': typeof DashAdminRuntimeLocationsRoute
  '/_dash/admin/tenants': typeof DashAdminTenantsRoute
  '/_dash/admin/users': typeof DashAdminUsersRoute
  '/_dash/agents/$executionId': typeof DashAgentsExecutionIdRoute
  '/_dash/alerts/$id': typeof DashAlertsIdRoute
  '/_dash/assets/$tab': typeof DashAssetsTabRoute
  '/_dash/cases/$id': typeof DashCasesIdRoute
  '/_dash/detection/ioc-types': typeof DashDetectionIocTypesRoute
  '/_dash/detection/mitre': typeof DashDetectionMitreRoute
  '/_dash/detection/pipelines': typeof DashDetectionPipelinesRoute
  '/_dash/detection/sigma': typeof DashDetectionSigmaRoute
  '/_dash/detection/threat-feeds': typeof DashDetectionThreatFeedsRoute
  '/_dash/incidents-simple/$id': typeof DashIncidentsSimpleIdRoute
  '/_dash/incidents/$id': typeof DashIncidentsIdRoute
  '/_dash/incidents/custom-fields': typeof DashIncidentsCustomFieldsRoute
  '/_dash/incidents/ioc-types': typeof DashIncidentsIocTypesRoute
  '/_dash/incidents/observables': typeof DashIncidentsObservablesRoute
  '/_dash/incidents/response-actions': typeof DashIncidentsResponseActionsRoute
  '/_dash/incidents/threat-feeds': typeof DashIncidentsThreatFeedsRoute
  '/_dash/jobs/$id': typeof DashJobsIdRoute
  '/_dash/monitors/response': typeof DashMonitorsResponseRoute
  '/_dash/monitors/terminal': typeof DashMonitorsTerminalRoute
  '/_dash/packages/$': typeof DashPackagesSplatRoute
  '/_dash/software/$': typeof DashSoftwareSplatRoute
  '/_dash/tickets/$id': typeof DashTicketsIdRoute
  '/_dash/workflows/$id': typeof DashWorkflowsIdRoute
  '/_dash/workflows/debug': typeof DashWorkflowsDebugRoute
  '/_onboarding/onboarding/authenticate': typeof OnboardingOnboardingAuthenticateRoute
  '/_onboarding/onboarding/automate': typeof OnboardingOnboardingAutomateRoute
  '/_onboarding/onboarding/product': typeof OnboardingOnboardingProductRoute
  '/_onboarding/onboarding/sources': typeof OnboardingOnboardingSourcesRoute
  '/_onboarding/onboarding/welcome': typeof OnboardingOnboardingWelcomeRoute
  '/login/$url/mfa-setup': typeof LoginUrlMfaSetupRoute
  '/_cond/forms/': typeof CondFormsIndexRoute
  '/_cond/usecases/': typeof CondUsecasesIndexRoute
  '/_cond/vulnerabilities/': typeof CondVulnerabilitiesIndexRoute
  '/_dash/admin/': typeof DashAdminIndexRoute
  '/_dash/agents/': typeof DashAgentsIndexRoute
  '/_dash/alerts/': typeof DashAlertsIndexRoute
  '/_dash/assets/': typeof DashAssetsIndexRoute
  '/_dash/cases/': typeof DashCasesIndexRoute
  '/_dash/detection/': typeof DashDetectionIndexRoute
  '/_dash/incidents-simple/': typeof DashIncidentsSimpleIndexRoute
  '/_dash/incidents/': typeof DashIncidentsIndexRoute
  '/_dash/infrastructure/': typeof DashInfrastructureIndexRoute
  '/_dash/jobs/': typeof DashJobsIndexRoute
  '/_dash/monitors/': typeof DashMonitorsIndexRoute
  '/_dash/tickets/': typeof DashTicketsIndexRoute
  '/_dash/workflows/': typeof DashWorkflowsIndexRoute
  '/_onboarding/onboarding/': typeof OnboardingOnboardingIndexRoute
  '/_cond/usecases/$flowId/details': typeof CondUsecasesFlowIdDetailsRoute
  '/_dash/infrastructure/flows/$flowId': typeof DashInfrastructureFlowsFlowIdRoute
  '/_dash/monitors/$id/terminal': typeof DashMonitorsIdTerminalRoute
  '/_cond/usecases/$flowId/': typeof CondUsecasesFlowIdIndexRoute
  '/_dash/monitors/$id/': typeof DashMonitorsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminsetup'
    | '/apps'
    | '/login'
    | '/mobile-login'
    | '/pricing'
    | '/register'
    | '/shuffle-core'
    | '/shuffle-core-demo'
    | '/shuffle-mcp-demo'
    | '/shuffle-mcps'
    | '/search'
    | '/agent'
    | '/dashboard'
    | '/dashboard-view'
    | '/organizations'
    | '/preferences'
    | '/settings'
    | '/templates'
    | '/users'
    | '/articles/$name'
    | '/blog/$name'
    | '/docs/$slug'
    | '/legal/$slug'
    | '/oauth2/authorize'
    | '/passwordreset/$key'
    | '/articles/'
    | '/blog/'
    | '/docs/'
    | '/legal/'
    | '/apps/$appname'
    | '/forms/$id'
    | '/vulnerabilities/$'
    | '/admin/datastore'
    | '/admin/locations'
    | '/admin/preferences'
    | '/admin/runtime-locations'
    | '/admin/tenants'
    | '/admin/users'
    | '/agents/$executionId'
    | '/alerts/$id'
    | '/assets/$tab'
    | '/cases/$id'
    | '/detection/ioc-types'
    | '/detection/mitre'
    | '/detection/pipelines'
    | '/detection/sigma'
    | '/detection/threat-feeds'
    | '/incidents-simple/$id'
    | '/incidents/$id'
    | '/incidents/custom-fields'
    | '/incidents/ioc-types'
    | '/incidents/observables'
    | '/incidents/response-actions'
    | '/incidents/threat-feeds'
    | '/jobs/$id'
    | '/monitors/response'
    | '/monitors/terminal'
    | '/packages/$'
    | '/software/$'
    | '/tickets/$id'
    | '/workflows/$id'
    | '/workflows/debug'
    | '/onboarding/authenticate'
    | '/onboarding/automate'
    | '/onboarding/product'
    | '/onboarding/sources'
    | '/onboarding/welcome'
    | '/login/$url/mfa-setup'
    | '/forms/'
    | '/usecases/'
    | '/vulnerabilities/'
    | '/admin/'
    | '/agents/'
    | '/alerts/'
    | '/assets/'
    | '/cases/'
    | '/detection/'
    | '/incidents-simple/'
    | '/incidents/'
    | '/infrastructure/'
    | '/jobs/'
    | '/monitors/'
    | '/tickets/'
    | '/workflows/'
    | '/onboarding/'
    | '/usecases/$flowId/details'
    | '/infrastructure/flows/$flowId'
    | '/monitors/$id/terminal'
    | '/usecases/$flowId/'
    | '/monitors/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminsetup'
    | '/apps'
    | '/login'
    | '/mobile-login'
    | '/pricing'
    | '/register'
    | '/shuffle-core'
    | '/shuffle-core-demo'
    | '/shuffle-mcp-demo'
    | '/shuffle-mcps'
    | '/search'
    | '/agent'
    | '/dashboard'
    | '/dashboard-view'
    | '/organizations'
    | '/preferences'
    | '/settings'
    | '/templates'
    | '/users'
    | '/articles/$name'
    | '/blog/$name'
    | '/docs/$slug'
    | '/legal/$slug'
    | '/oauth2/authorize'
    | '/passwordreset/$key'
    | '/articles'
    | '/blog'
    | '/docs'
    | '/legal'
    | '/apps/$appname'
    | '/forms/$id'
    | '/vulnerabilities/$'
    | '/admin/datastore'
    | '/admin/locations'
    | '/admin/preferences'
    | '/admin/runtime-locations'
    | '/admin/tenants'
    | '/admin/users'
    | '/agents/$executionId'
    | '/alerts/$id'
    | '/assets/$tab'
    | '/cases/$id'
    | '/detection/ioc-types'
    | '/detection/mitre'
    | '/detection/pipelines'
    | '/detection/sigma'
    | '/detection/threat-feeds'
    | '/incidents-simple/$id'
    | '/incidents/$id'
    | '/incidents/custom-fields'
    | '/incidents/ioc-types'
    | '/incidents/observables'
    | '/incidents/response-actions'
    | '/incidents/threat-feeds'
    | '/jobs/$id'
    | '/monitors/response'
    | '/monitors/terminal'
    | '/packages/$'
    | '/software/$'
    | '/tickets/$id'
    | '/workflows/$id'
    | '/workflows/debug'
    | '/onboarding/authenticate'
    | '/onboarding/automate'
    | '/onboarding/product'
    | '/onboarding/sources'
    | '/onboarding/welcome'
    | '/login/$url/mfa-setup'
    | '/forms'
    | '/usecases'
    | '/vulnerabilities'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/assets'
    | '/cases'
    | '/detection'
    | '/incidents-simple'
    | '/incidents'
    | '/infrastructure'
    | '/jobs'
    | '/monitors'
    | '/tickets'
    | '/workflows'
    | '/onboarding'
    | '/usecases/$flowId/details'
    | '/infrastructure/flows/$flowId'
    | '/monitors/$id/terminal'
    | '/usecases/$flowId'
    | '/monitors/$id'
  id:
    | '__root__'
    | '/'
    | '/_cond'
    | '/_dash'
    | '/_onboarding'
    | '/adminsetup'
    | '/apps'
    | '/login'
    | '/mobile-login'
    | '/pricing'
    | '/register'
    | '/shuffle-core'
    | '/shuffle-core-demo'
    | '/shuffle-mcp-demo'
    | '/shuffle-mcps'
    | '/_cond/search'
    | '/_dash/agent'
    | '/_dash/dashboard'
    | '/_dash/dashboard-view'
    | '/_dash/organizations'
    | '/_dash/preferences'
    | '/_dash/settings'
    | '/_dash/templates'
    | '/_dash/users'
    | '/articles/$name'
    | '/blog/$name'
    | '/docs/$slug'
    | '/legal/$slug'
    | '/oauth2/authorize'
    | '/passwordreset/$key'
    | '/articles/'
    | '/blog/'
    | '/docs/'
    | '/legal/'
    | '/_cond/apps/$appname'
    | '/_cond/forms/$id'
    | '/_cond/vulnerabilities/$'
    | '/_dash/admin/datastore'
    | '/_dash/admin/locations'
    | '/_dash/admin/preferences'
    | '/_dash/admin/runtime-locations'
    | '/_dash/admin/tenants'
    | '/_dash/admin/users'
    | '/_dash/agents/$executionId'
    | '/_dash/alerts/$id'
    | '/_dash/assets/$tab'
    | '/_dash/cases/$id'
    | '/_dash/detection/ioc-types'
    | '/_dash/detection/mitre'
    | '/_dash/detection/pipelines'
    | '/_dash/detection/sigma'
    | '/_dash/detection/threat-feeds'
    | '/_dash/incidents-simple/$id'
    | '/_dash/incidents/$id'
    | '/_dash/incidents/custom-fields'
    | '/_dash/incidents/ioc-types'
    | '/_dash/incidents/observables'
    | '/_dash/incidents/response-actions'
    | '/_dash/incidents/threat-feeds'
    | '/_dash/jobs/$id'
    | '/_dash/monitors/response'
    | '/_dash/monitors/terminal'
    | '/_dash/packages/$'
    | '/_dash/software/$'
    | '/_dash/tickets/$id'
    | '/_dash/workflows/$id'
    | '/_dash/workflows/debug'
    | '/_onboarding/onboarding/authenticate'
    | '/_onboarding/onboarding/automate'
    | '/_onboarding/onboarding/product'
    | '/_onboarding/onboarding/sources'
    | '/_onboarding/onboarding/welcome'
    | '/login/$url/mfa-setup'
    | '/_cond/forms/'
    | '/_cond/usecases/'
    | '/_cond/vulnerabilities/'
    | '/_dash/admin/'
    | '/_dash/agents/'
    | '/_dash/alerts/'
    | '/_dash/assets/'
    | '/_dash/cases/'
    | '/_dash/detection/'
    | '/_dash/incidents-simple/'
    | '/_dash/incidents/'
    | '/_dash/infrastructure/'
    | '/_dash/jobs/'
    | '/_dash/monitors/'
    | '/_dash/tickets/'
    | '/_dash/workflows/'
    | '/_onboarding/onboarding/'
    | '/_cond/usecases/$flowId/details'
    | '/_dash/infrastructure/flows/$flowId'
    | '/_dash/monitors/$id/terminal'
    | '/_cond/usecases/$flowId/'
    | '/_dash/monitors/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CondRoute: typeof CondRouteWithChildren
  DashRoute: typeof DashRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  AdminsetupRoute: typeof AdminsetupRoute
  AppsRoute: typeof AppsRoute
  LoginRoute: typeof LoginRouteWithChildren
  MobileLoginRoute: typeof MobileLoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ShuffleCoreRoute: typeof ShuffleCoreRoute
  ShuffleCoreDemoRoute: typeof ShuffleCoreDemoRoute
  ShuffleMcpDemoRoute: typeof ShuffleMcpDemoRoute
  ShuffleMcpsRoute: typeof ShuffleMcpsRoute
  ArticlesNameRoute: typeof ArticlesNameRoute
  BlogNameRoute: typeof BlogNameRoute
  DocsSlugRoute: typeof DocsSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  Oauth2AuthorizeRoute: typeof Oauth2AuthorizeRoute
  PasswordresetKeyRoute: typeof PasswordresetKeyRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_cond': {
      id: '/_cond'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminsetup': {
      id: '/adminsetup'
      path: '/adminsetup'
      fullPath: '/adminsetup'
      preLoaderRoute: typeof AdminsetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-login': {
      id: '/mobile-login'
      path: '/mobile-login'
      fullPath: '/mobile-login'
      preLoaderRoute: typeof MobileLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuffle-core': {
      id: '/shuffle-core'
      path: '/shuffle-core'
      fullPath: '/shuffle-core'
      preLoaderRoute: typeof ShuffleCoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuffle-core-demo': {
      id: '/shuffle-core-demo'
      path: '/shuffle-core-demo'
      fullPath: '/shuffle-core-demo'
      preLoaderRoute: typeof ShuffleCoreDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuffle-mcp-demo': {
      id: '/shuffle-mcp-demo'
      path: '/shuffle-mcp-demo'
      fullPath: '/shuffle-mcp-demo'
      preLoaderRoute: typeof ShuffleMcpDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuffle-mcps': {
      id: '/shuffle-mcps'
      path: '/shuffle-mcps'
      fullPath: '/shuffle-mcps'
      preLoaderRoute: typeof ShuffleMcpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_cond/search': {
      id: '/_cond/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof CondSearchRouteImport
      parentRoute: typeof CondRoute
    }
    '/_dash/agent': {
      id: '/_dash/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof DashAgentRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard-view': {
      id: '/_dash/dashboard-view'
      path: '/dashboard-view'
      fullPath: '/dashboard-view'
      preLoaderRoute: typeof DashDashboardViewRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/organizations': {
      id: '/_dash/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof DashOrganizationsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/preferences': {
      id: '/_dash/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof DashPreferencesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/settings': {
      id: '/_dash/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/templates': {
      id: '/_dash/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof DashTemplatesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/users': {
      id: '/_dash/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashUsersRouteImport
      parentRoute: typeof DashRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$name': {
      id: '/articles/$name'
      path: '/articles/$name'
      fullPath: '/articles/$name'
      preLoaderRoute: typeof ArticlesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$name': {
      id: '/blog/$name'
      path: '/blog/$name'
      fullPath: '/blog/$name'
      preLoaderRoute: typeof BlogNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2/authorize': {
      id: '/oauth2/authorize'
      path: '/oauth2/authorize'
      fullPath: '/oauth2/authorize'
      preLoaderRoute: typeof Oauth2AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwordreset/$key': {
      id: '/passwordreset/$key'
      path: '/passwordreset/$key'
      fullPath: '/passwordreset/$key'
      preLoaderRoute: typeof PasswordresetKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_cond/apps/$appname': {
      id: '/_cond/apps/$appname'
      path: '/apps/$appname'
      fullPath: '/apps/$appname'
      preLoaderRoute: typeof CondAppsAppnameRouteImport
      parentRoute: typeof CondRoute
    }
    '/_cond/forms/': {
      id: '/_cond/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof CondFormsIndexRouteImport
      parentRoute: typeof CondRoute
    }
    '/_cond/forms/$id': {
      id: '/_cond/forms/$id'
      path: '/forms/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof CondFormsIdRouteImport
      parentRoute: typeof CondRoute
    }
    '/_cond/usecases/': {
      id: '/_cond/usecases/'
      path: '/usecases'
      fullPath: '/usecases/'
      preLoaderRoute: typeof CondUsecasesIndexRouteImport
      parentRoute: typeof CondRoute
    }
    '/_cond/vulnerabilities/': {
      id: '/_cond/vulnerabilities/'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities/'
      preLoaderRoute: typeof CondVulnerabilitiesIndexRouteImport
      parentRoute: typeof CondRoute
    }
    '/_cond/vulnerabilities/$': {
      id: '/_cond/vulnerabilities/$'
      path: '/vulnerabilities/$'
      fullPath: '/vulnerabilities/$'
      preLoaderRoute: typeof CondVulnerabilitiesSplatRouteImport
      parentRoute: typeof CondRoute
    }
    '/_dash/admin/': {
      id: '/_dash/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof DashAdminIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin/datastore': {
      id: '/_dash/admin/datastore'
      path: '/admin/datastore'
      fullPath: '/admin/datastore'
      preLoaderRoute: typeof DashAdminDatastoreRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin/locations': {
      id: '/_dash/admin/locations'
      path: '/admin/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof DashAdminLocationsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin/preferences': {
      id: '/_dash/admin/preferences'
      path: '/admin/preferences'
      fullPath: '/admin/preferences'
      preLoaderRoute: typeof DashAdminPreferencesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin/runtime-locations': {
      id: '/_dash/admin/runtime-locations'
      path: '/admin/runtime-locations'
      fullPath: '/admin/runtime-locations'
      preLoaderRoute: typeof DashAdminRuntimeLocationsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin/tenants': {
      id: '/_dash/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof DashAdminTenantsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin/users': {
      id: '/_dash/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof DashAdminUsersRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/agents/': {
      id: '/_dash/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof DashAgentsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/agents/$executionId': {
      id: '/_dash/agents/$executionId'
      path: '/agents/$executionId'
      fullPath: '/agents/$executionId'
      preLoaderRoute: typeof DashAgentsExecutionIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/alerts/': {
      id: '/_dash/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof DashAlertsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/alerts/$id': {
      id: '/_dash/alerts/$id'
      path: '/alerts/$id'
      fullPath: '/alerts/$id'
      preLoaderRoute: typeof DashAlertsIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/assets/': {
      id: '/_dash/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof DashAssetsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/assets/$tab': {
      id: '/_dash/assets/$tab'
      path: '/assets/$tab'
      fullPath: '/assets/$tab'
      preLoaderRoute: typeof DashAssetsTabRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/cases/': {
      id: '/_dash/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof DashCasesIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/cases/$id': {
      id: '/_dash/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof DashCasesIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/detection/': {
      id: '/_dash/detection/'
      path: '/detection'
      fullPath: '/detection/'
      preLoaderRoute: typeof DashDetectionIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/detection/ioc-types': {
      id: '/_dash/detection/ioc-types'
      path: '/detection/ioc-types'
      fullPath: '/detection/ioc-types'
      preLoaderRoute: typeof DashDetectionIocTypesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/detection/mitre': {
      id: '/_dash/detection/mitre'
      path: '/detection/mitre'
      fullPath: '/detection/mitre'
      preLoaderRoute: typeof DashDetectionMitreRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/detection/pipelines': {
      id: '/_dash/detection/pipelines'
      path: '/detection/pipelines'
      fullPath: '/detection/pipelines'
      preLoaderRoute: typeof DashDetectionPipelinesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/detection/sigma': {
      id: '/_dash/detection/sigma'
      path: '/detection/sigma'
      fullPath: '/detection/sigma'
      preLoaderRoute: typeof DashDetectionSigmaRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/detection/threat-feeds': {
      id: '/_dash/detection/threat-feeds'
      path: '/detection/threat-feeds'
      fullPath: '/detection/threat-feeds'
      preLoaderRoute: typeof DashDetectionThreatFeedsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/incidents-simple/': {
      id: '/_dash/incidents-simple/'
      path: '/incidents-simple'
      fullPath: '/incidents-simple/'
      preLoaderRoute: typeof DashIncidentsSimpleIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/incidents-simple/$id': {
      id: '/_dash/incidents-simple/$id'
      path: '/incidents-simple/$id'
      fullPath: '/incidents-simple/$id'
      preLoaderRoute: typeof DashIncidentsSimpleIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/incidents/': {
      id: '/_dash/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof DashIncidentsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/incidents/$id': {
      id: '/_dash/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof DashIncidentsIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/incidents/custom-fields': {
      id: '/_dash/incidents/custom-fields'
      path: '/incidents/custom-fields'
      fullPath: '/incidents/custom-fields'
      preLoaderRoute: typeof DashIncidentsCustomFieldsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/incidents/ioc-types': {
      id: '/_dash/incidents/ioc-types'
      path: '/incidents/ioc-types'
      fullPath: '/incidents/ioc-types'
      preLoaderRoute: typeof DashIncidentsIocTypesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/incidents/observables': {
      id: '/_dash/incidents/observables'
      path: '/incidents/observables'
      fullPath: '/incidents/observables'
      preLoaderRoute: typeof DashIncidentsObservablesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/incidents/response-actions': {
      id: '/_dash/incidents/response-actions'
      path: '/incidents/response-actions'
      fullPath: '/incidents/response-actions'
      preLoaderRoute: typeof DashIncidentsResponseActionsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/incidents/threat-feeds': {
      id: '/_dash/incidents/threat-feeds'
      path: '/incidents/threat-feeds'
      fullPath: '/incidents/threat-feeds'
      preLoaderRoute: typeof DashIncidentsThreatFeedsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/infrastructure/': {
      id: '/_dash/infrastructure/'
      path: '/infrastructure'
      fullPath: '/infrastructure/'
      preLoaderRoute: typeof DashInfrastructureIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/jobs/': {
      id: '/_dash/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof DashJobsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/jobs/$id': {
      id: '/_dash/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof DashJobsIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/monitors/': {
      id: '/_dash/monitors/'
      path: '/monitors'
      fullPath: '/monitors/'
      preLoaderRoute: typeof DashMonitorsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/monitors/response': {
      id: '/_dash/monitors/response'
      path: '/monitors/response'
      fullPath: '/monitors/response'
      preLoaderRoute: typeof DashMonitorsResponseRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/monitors/terminal': {
      id: '/_dash/monitors/terminal'
      path: '/monitors/terminal'
      fullPath: '/monitors/terminal'
      preLoaderRoute: typeof DashMonitorsTerminalRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/packages/$': {
      id: '/_dash/packages/$'
      path: '/packages/$'
      fullPath: '/packages/$'
      preLoaderRoute: typeof DashPackagesSplatRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/software/$': {
      id: '/_dash/software/$'
      path: '/software/$'
      fullPath: '/software/$'
      preLoaderRoute: typeof DashSoftwareSplatRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/tickets/': {
      id: '/_dash/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof DashTicketsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/tickets/$id': {
      id: '/_dash/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof DashTicketsIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/workflows/': {
      id: '/_dash/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof DashWorkflowsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/workflows/$id': {
      id: '/_dash/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof DashWorkflowsIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/workflows/debug': {
      id: '/_dash/workflows/debug'
      path: '/workflows/debug'
      fullPath: '/workflows/debug'
      preLoaderRoute: typeof DashWorkflowsDebugRouteImport
      parentRoute: typeof DashRoute
    }
    '/_onboarding/onboarding/': {
      id: '/_onboarding/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingOnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/onboarding/authenticate': {
      id: '/_onboarding/onboarding/authenticate'
      path: '/onboarding/authenticate'
      fullPath: '/onboarding/authenticate'
      preLoaderRoute: typeof OnboardingOnboardingAuthenticateRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/onboarding/automate': {
      id: '/_onboarding/onboarding/automate'
      path: '/onboarding/automate'
      fullPath: '/onboarding/automate'
      preLoaderRoute: typeof OnboardingOnboardingAutomateRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/onboarding/product': {
      id: '/_onboarding/onboarding/product'
      path: '/onboarding/product'
      fullPath: '/onboarding/product'
      preLoaderRoute: typeof OnboardingOnboardingProductRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/onboarding/sources': {
      id: '/_onboarding/onboarding/sources'
      path: '/onboarding/sources'
      fullPath: '/onboarding/sources'
      preLoaderRoute: typeof OnboardingOnboardingSourcesRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/onboarding/welcome': {
      id: '/_onboarding/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingOnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/login/$url/mfa-setup': {
      id: '/login/$url/mfa-setup'
      path: '/$url/mfa-setup'
      fullPath: '/login/$url/mfa-setup'
      preLoaderRoute: typeof LoginUrlMfaSetupRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_cond/usecases/$flowId/': {
      id: '/_cond/usecases/$flowId/'
      path: '/usecases/$flowId'
      fullPath: '/usecases/$flowId/'
      preLoaderRoute: typeof CondUsecasesFlowIdIndexRouteImport
      parentRoute: typeof CondRoute
    }
    '/_cond/usecases/$flowId/details': {
      id: '/_cond/usecases/$flowId/details'
      path: '/usecases/$flowId/details'
      fullPath: '/usecases/$flowId/details'
      preLoaderRoute: typeof CondUsecasesFlowIdDetailsRouteImport
      parentRoute: typeof CondRoute
    }
    '/_dash/infrastructure/flows/$flowId': {
      id: '/_dash/infrastructure/flows/$flowId'
      path: '/infrastructure/flows/$flowId'
      fullPath: '/infrastructure/flows/$flowId'
      preLoaderRoute: typeof DashInfrastructureFlowsFlowIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/monitors/$id/': {
      id: '/_dash/monitors/$id/'
      path: '/monitors/$id'
      fullPath: '/monitors/$id/'
      preLoaderRoute: typeof DashMonitorsIdIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/monitors/$id/terminal': {
      id: '/_dash/monitors/$id/terminal'
      path: '/monitors/$id/terminal'
      fullPath: '/monitors/$id/terminal'
      preLoaderRoute: typeof DashMonitorsIdTerminalRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface CondRouteChildren {
  CondSearchRoute: typeof CondSearchRoute
  CondAppsAppnameRoute: typeof CondAppsAppnameRoute
  CondFormsIdRoute: typeof CondFormsIdRoute
  CondVulnerabilitiesSplatRoute: typeof CondVulnerabilitiesSplatRoute
  CondFormsIndexRoute: typeof CondFormsIndexRoute
  CondUsecasesIndexRoute: typeof CondUsecasesIndexRoute
  CondVulnerabilitiesIndexRoute: typeof CondVulnerabilitiesIndexRoute
  CondUsecasesFlowIdDetailsRoute: typeof CondUsecasesFlowIdDetailsRoute
  CondUsecasesFlowIdIndexRoute: typeof CondUsecasesFlowIdIndexRoute
}

const CondRouteChildren: CondRouteChildren = {
  CondSearchRoute: CondSearchRoute,
  CondAppsAppnameRoute: CondAppsAppnameRoute,
  CondFormsIdRoute: CondFormsIdRoute,
  CondVulnerabilitiesSplatRoute: CondVulnerabilitiesSplatRoute,
  CondFormsIndexRoute: CondFormsIndexRoute,
  CondUsecasesIndexRoute: CondUsecasesIndexRoute,
  CondVulnerabilitiesIndexRoute: CondVulnerabilitiesIndexRoute,
  CondUsecasesFlowIdDetailsRoute: CondUsecasesFlowIdDetailsRoute,
  CondUsecasesFlowIdIndexRoute: CondUsecasesFlowIdIndexRoute,
}

const CondRouteWithChildren = CondRoute._addFileChildren(CondRouteChildren)

interface DashRouteChildren {
  DashAgentRoute: typeof DashAgentRoute
  DashDashboardRoute: typeof DashDashboardRoute
  DashDashboardViewRoute: typeof DashDashboardViewRoute
  DashOrganizationsRoute: typeof DashOrganizationsRoute
  DashPreferencesRoute: typeof DashPreferencesRoute
  DashSettingsRoute: typeof DashSettingsRoute
  DashTemplatesRoute: typeof DashTemplatesRoute
  DashUsersRoute: typeof DashUsersRoute
  DashAdminDatastoreRoute: typeof DashAdminDatastoreRoute
  DashAdminLocationsRoute: typeof DashAdminLocationsRoute
  DashAdminPreferencesRoute: typeof DashAdminPreferencesRoute
  DashAdminRuntimeLocationsRoute: typeof DashAdminRuntimeLocationsRoute
  DashAdminTenantsRoute: typeof DashAdminTenantsRoute
  DashAdminUsersRoute: typeof DashAdminUsersRoute
  DashAgentsExecutionIdRoute: typeof DashAgentsExecutionIdRoute
  DashAlertsIdRoute: typeof DashAlertsIdRoute
  DashAssetsTabRoute: typeof DashAssetsTabRoute
  DashCasesIdRoute: typeof DashCasesIdRoute
  DashDetectionIocTypesRoute: typeof DashDetectionIocTypesRoute
  DashDetectionMitreRoute: typeof DashDetectionMitreRoute
  DashDetectionPipelinesRoute: typeof DashDetectionPipelinesRoute
  DashDetectionSigmaRoute: typeof DashDetectionSigmaRoute
  DashDetectionThreatFeedsRoute: typeof DashDetectionThreatFeedsRoute
  DashIncidentsSimpleIdRoute: typeof DashIncidentsSimpleIdRoute
  DashIncidentsIdRoute: typeof DashIncidentsIdRoute
  DashIncidentsCustomFieldsRoute: typeof DashIncidentsCustomFieldsRoute
  DashIncidentsIocTypesRoute: typeof DashIncidentsIocTypesRoute
  DashIncidentsObservablesRoute: typeof DashIncidentsObservablesRoute
  DashIncidentsResponseActionsRoute: typeof DashIncidentsResponseActionsRoute
  DashIncidentsThreatFeedsRoute: typeof DashIncidentsThreatFeedsRoute
  DashJobsIdRoute: typeof DashJobsIdRoute
  DashMonitorsResponseRoute: typeof DashMonitorsResponseRoute
  DashMonitorsTerminalRoute: typeof DashMonitorsTerminalRoute
  DashPackagesSplatRoute: typeof DashPackagesSplatRoute
  DashSoftwareSplatRoute: typeof DashSoftwareSplatRoute
  DashTicketsIdRoute: typeof DashTicketsIdRoute
  DashWorkflowsIdRoute: typeof DashWorkflowsIdRoute
  DashWorkflowsDebugRoute: typeof DashWorkflowsDebugRoute
  DashAdminIndexRoute: typeof DashAdminIndexRoute
  DashAgentsIndexRoute: typeof DashAgentsIndexRoute
  DashAlertsIndexRoute: typeof DashAlertsIndexRoute
  DashAssetsIndexRoute: typeof DashAssetsIndexRoute
  DashCasesIndexRoute: typeof DashCasesIndexRoute
  DashDetectionIndexRoute: typeof DashDetectionIndexRoute
  DashIncidentsSimpleIndexRoute: typeof DashIncidentsSimpleIndexRoute
  DashIncidentsIndexRoute: typeof DashIncidentsIndexRoute
  DashInfrastructureIndexRoute: typeof DashInfrastructureIndexRoute
  DashJobsIndexRoute: typeof DashJobsIndexRoute
  DashMonitorsIndexRoute: typeof DashMonitorsIndexRoute
  DashTicketsIndexRoute: typeof DashTicketsIndexRoute
  DashWorkflowsIndexRoute: typeof DashWorkflowsIndexRoute
  DashInfrastructureFlowsFlowIdRoute: typeof DashInfrastructureFlowsFlowIdRoute
  DashMonitorsIdTerminalRoute: typeof DashMonitorsIdTerminalRoute
  DashMonitorsIdIndexRoute: typeof DashMonitorsIdIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAgentRoute: DashAgentRoute,
  DashDashboardRoute: DashDashboardRoute,
  DashDashboardViewRoute: DashDashboardViewRoute,
  DashOrganizationsRoute: DashOrganizationsRoute,
  DashPreferencesRoute: DashPreferencesRoute,
  DashSettingsRoute: DashSettingsRoute,
  DashTemplatesRoute: DashTemplatesRoute,
  DashUsersRoute: DashUsersRoute,
  DashAdminDatastoreRoute: DashAdminDatastoreRoute,
  DashAdminLocationsRoute: DashAdminLocationsRoute,
  DashAdminPreferencesRoute: DashAdminPreferencesRoute,
  DashAdminRuntimeLocationsRoute: DashAdminRuntimeLocationsRoute,
  DashAdminTenantsRoute: DashAdminTenantsRoute,
  DashAdminUsersRoute: DashAdminUsersRoute,
  DashAgentsExecutionIdRoute: DashAgentsExecutionIdRoute,
  DashAlertsIdRoute: DashAlertsIdRoute,
  DashAssetsTabRoute: DashAssetsTabRoute,
  DashCasesIdRoute: DashCasesIdRoute,
  DashDetectionIocTypesRoute: DashDetectionIocTypesRoute,
  DashDetectionMitreRoute: DashDetectionMitreRoute,
  DashDetectionPipelinesRoute: DashDetectionPipelinesRoute,
  DashDetectionSigmaRoute: DashDetectionSigmaRoute,
  DashDetectionThreatFeedsRoute: DashDetectionThreatFeedsRoute,
  DashIncidentsSimpleIdRoute: DashIncidentsSimpleIdRoute,
  DashIncidentsIdRoute: DashIncidentsIdRoute,
  DashIncidentsCustomFieldsRoute: DashIncidentsCustomFieldsRoute,
  DashIncidentsIocTypesRoute: DashIncidentsIocTypesRoute,
  DashIncidentsObservablesRoute: DashIncidentsObservablesRoute,
  DashIncidentsResponseActionsRoute: DashIncidentsResponseActionsRoute,
  DashIncidentsThreatFeedsRoute: DashIncidentsThreatFeedsRoute,
  DashJobsIdRoute: DashJobsIdRoute,
  DashMonitorsResponseRoute: DashMonitorsResponseRoute,
  DashMonitorsTerminalRoute: DashMonitorsTerminalRoute,
  DashPackagesSplatRoute: DashPackagesSplatRoute,
  DashSoftwareSplatRoute: DashSoftwareSplatRoute,
  DashTicketsIdRoute: DashTicketsIdRoute,
  DashWorkflowsIdRoute: DashWorkflowsIdRoute,
  DashWorkflowsDebugRoute: DashWorkflowsDebugRoute,
  DashAdminIndexRoute: DashAdminIndexRoute,
  DashAgentsIndexRoute: DashAgentsIndexRoute,
  DashAlertsIndexRoute: DashAlertsIndexRoute,
  DashAssetsIndexRoute: DashAssetsIndexRoute,
  DashCasesIndexRoute: DashCasesIndexRoute,
  DashDetectionIndexRoute: DashDetectionIndexRoute,
  DashIncidentsSimpleIndexRoute: DashIncidentsSimpleIndexRoute,
  DashIncidentsIndexRoute: DashIncidentsIndexRoute,
  DashInfrastructureIndexRoute: DashInfrastructureIndexRoute,
  DashJobsIndexRoute: DashJobsIndexRoute,
  DashMonitorsIndexRoute: DashMonitorsIndexRoute,
  DashTicketsIndexRoute: DashTicketsIndexRoute,
  DashWorkflowsIndexRoute: DashWorkflowsIndexRoute,
  DashInfrastructureFlowsFlowIdRoute: DashInfrastructureFlowsFlowIdRoute,
  DashMonitorsIdTerminalRoute: DashMonitorsIdTerminalRoute,
  DashMonitorsIdIndexRoute: DashMonitorsIdIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

interface OnboardingRouteChildren {
  OnboardingOnboardingAuthenticateRoute: typeof OnboardingOnboardingAuthenticateRoute
  OnboardingOnboardingAutomateRoute: typeof OnboardingOnboardingAutomateRoute
  OnboardingOnboardingProductRoute: typeof OnboardingOnboardingProductRoute
  OnboardingOnboardingSourcesRoute: typeof OnboardingOnboardingSourcesRoute
  OnboardingOnboardingWelcomeRoute: typeof OnboardingOnboardingWelcomeRoute
  OnboardingOnboardingIndexRoute: typeof OnboardingOnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingOnboardingAuthenticateRoute: OnboardingOnboardingAuthenticateRoute,
  OnboardingOnboardingAutomateRoute: OnboardingOnboardingAutomateRoute,
  OnboardingOnboardingProductRoute: OnboardingOnboardingProductRoute,
  OnboardingOnboardingSourcesRoute: OnboardingOnboardingSourcesRoute,
  OnboardingOnboardingWelcomeRoute: OnboardingOnboardingWelcomeRoute,
  OnboardingOnboardingIndexRoute: OnboardingOnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface LoginRouteChildren {
  LoginUrlMfaSetupRoute: typeof LoginUrlMfaSetupRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginUrlMfaSetupRoute: LoginUrlMfaSetupRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CondRoute: CondRouteWithChildren,
  DashRoute: DashRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  AdminsetupRoute: AdminsetupRoute,
  AppsRoute: AppsRoute,
  LoginRoute: LoginRouteWithChildren,
  MobileLoginRoute: MobileLoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ShuffleCoreRoute: ShuffleCoreRoute,
  ShuffleCoreDemoRoute: ShuffleCoreDemoRoute,
  ShuffleMcpDemoRoute: ShuffleMcpDemoRoute,
  ShuffleMcpsRoute: ShuffleMcpsRoute,
  ArticlesNameRoute: ArticlesNameRoute,
  BlogNameRoute: BlogNameRoute,
  DocsSlugRoute: DocsSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  Oauth2AuthorizeRoute: Oauth2AuthorizeRoute,
  PasswordresetKeyRoute: PasswordresetKeyRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
